### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by zhanghaicheng1** [apache/incubator-kyuubi#1065]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

> ./bin/kyuubi run
When I run this command, it prompts that the port is occupied, but I don’t know which port is occupied

Looking forward to reply, thank you!

### Kyuubi Server Log Output

```logtalk
Starting Kyuubi Server from /opt/kyuuid/kyuubi-1.2.0-bin-without-spark
Warn: Not find kyuubi environment file /opt/kyuuid/kyuubi-1.2.0-bin-without-spark/conf/kyuubi-env.sh, using default ones...
JAVA_HOME: /opt/jdk1.8.0_172
KYUUBI_HOME: /opt/kyuuid/kyuubi-1.2.0-bin-without-spark
KYUUBI_CONF_DIR: /opt/kyuuid/kyuubi-1.2.0-bin-without-spark/conf
KYUUBI_LOG_DIR: /opt/kyuuid/kyuubi-1.2.0-bin-without-spark/logs
KYUUBI_PID_DIR: /opt/kyuuid/kyuubi-1.2.0-bin-without-spark/pid
KYUUBI_WORK_DIR_ROOT: /opt/kyuuid/kyuubi-1.2.0-bin-without-spark/work
SPARK_HOME: /opt/spark-3.1.2
SPARK_CONF_DIR: /opt/spark-3.1.2/conf
HADOOP_CONF_DIR: /etc/hadoop/conf
Starting org.apache.kyuubi.server.KyuubiServer
21/09/09 15:40:05 INFO server.KyuubiServer:
                  Welcome to
  __  __                           __
 /\ \/\ \                         /\ \      __
 \ \ \/'/'  __  __  __  __  __  __\ \ \____/\_\
  \ \ , <  /\ \/\ \/\ \/\ \/\ \/\ \\ \ '__`\/\ \
   \ \ \\`\\ \ \_\ \ \ \_\ \ \ \_\ \\ \ \L\ \ \ \
    \ \_\ \_\/`____ \ \____/\ \____/ \ \_,__/\ \_\
     \/_/\/_/`/___/> \/___/  \/___/   \/___/  \/_/
                /\___/
                \/__/

21/09/09 15:40:05 INFO server.KyuubiServer: Version: 1.2.0, Revision: a6ab236b33b5c8a86d4c2ed0e9fe8c8c73f81a1f, Branch: HEAD, Java: 1.8, Scala: 2.12, Spark: 3.1.2, Hadoop: 3.2.2, Hive: 2.3.7
21/09/09 15:40:06 INFO server.KyuubiServer: Using Scala version 2.12.10, Java HotSpot(TM) 64-Bit Server VM, 1.8.0_172
21/09/09 15:40:06 INFO util.SignalRegister: Registering signal handler for TERM
21/09/09 15:40:06 INFO util.SignalRegister: Registering signal handler for HUP
21/09/09 15:40:06 INFO util.SignalRegister: Registering signal handler for INT
21/09/09 15:40:06 INFO kyuubi.Utils: Loading Kyuubi properties from /opt/kyuuid/kyuubi-1.2.0-bin-without-spark/conf/kyuubi-defaults.conf
21/09/09 15:40:06 INFO zookeeper.EmbeddedZookeeper: Service[EmbeddedZookeeper] is initialized.
21/09/09 15:40:06 INFO server.ZooKeeperServerMain: Starting server
21/09/09 15:40:06 INFO server.ZooKeeperServer: Server environment:zookeeper.version=3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf, built on 03/06/2019 16:18 GMT
21/09/09 15:40:06 INFO server.ZooKeeperServer: Server environment:host.name=centos4
21/09/09 15:40:06 INFO server.ZooKeeperServer: Server environment:java.version=1.8.0_172
21/09/09 15:40:06 INFO server.ZooKeeperServer: Server environment:java.vendor=Oracle Corporation
21/09/09 15:40:06 INFO server.ZooKeeperServer: Server environment:java.home=/opt/jdk1.8.0_172/jre
21/09/09 15:40:06 INFO server.ZooKeeperServer: Server environment:java.class.path=/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/slf4j-api-1.7.30.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/libfb303-0.9.3.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/hadoop-client-api-3.2.2.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/curator-client-2.12.0.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/failureaccess-1.0.1.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/zookeeper-3.4.14.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/jetty-http-9.4.40.v20210413.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/simpleclient_dropwizard-0.10.0.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/simpleclient-0.10.0.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/commons-codec-1.15.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/curator-recipes-2.12.0.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/log4j-1.2.17.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/metrics-jvm-4.1.1.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/kyuubi-main-1.2.0.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/curator-test-2.12.0.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/javassist-3.18.1-GA.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/htrace-core4-4.1.0-incubating.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/simpleclient_servlet-0.10.0.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/kyuubi-common-1.2.0.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/jetty-security-9.4.40.v20210413.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/metrics-jmx-4.1.1.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/jetty-io-9.4.40.v20210413.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/curator-framework-2.12.0.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/jakarta.servlet-api-4.0.4.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/commons-lang3-3.10.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/jetty-server-9.4.40.v20210413.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/jackson-databind-2.11.4.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/jackson-core-2.11.4.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/hadoop-client-runtime-3.2.2.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/jcl-over-slf4j-1.7.30.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/kyuubi-metrics-1.2.0.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/metrics-json-4.1.1.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/kyuubi-ha-1.2.0.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/guava-30.1-jre.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/libthrift-0.9.3.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/metrics-core-4.1.1.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/hive-service-rpc-2.3.7.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/kyuubi-ctl-1.2.0.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/slf4j-log4j12-1.7.30.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/jackson-annotations-2.11.4.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/jetty-servlet-9.4.40.v20210413.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/simpleclient_common-0.10.0.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/scala-library-2.12.10.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/jetty-util-9.4.40.v20210413.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/kyuubi-zookeeper-1.2.0.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/jars/jetty-util-ajax-9.4.40.v20210413.jar:/opt/kyuuid/kyuubi-1.2.0-bin-without-spark/conf:/etc/hadoop/conf
21/09/09 15:40:06 INFO server.ZooKeeperServer: Server environment:java.library.path=:/opt/cloudera/parcels/CDH-6.1.1-1.cdh6.1.1.p0.875250/lib/hadoop/lib/native:/opt/cloudera/parcels/CDH-6.1.1-1.cdh6.1.1.p0.875250/lib/hadoop/lib/native:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
21/09/09 15:40:06 INFO server.ZooKeeperServer: Server environment:java.io.tmpdir=/tmp
21/09/09 15:40:06 INFO server.ZooKeeperServer: Server environment:java.compiler=<NA>
21/09/09 15:40:06 INFO server.ZooKeeperServer: Server environment:os.name=Linux
21/09/09 15:40:06 INFO server.ZooKeeperServer: Server environment:os.arch=amd64
21/09/09 15:40:06 INFO server.ZooKeeperServer: Server environment:os.version=3.10.0-957.27.2.el7.x86_64
21/09/09 15:40:06 INFO server.ZooKeeperServer: Server environment:user.name=root
21/09/09 15:40:06 INFO server.ZooKeeperServer: Server environment:user.home=/root
21/09/09 15:40:06 INFO server.ZooKeeperServer: Server environment:user.dir=/opt/kyuuid/kyuubi-1.2.0-bin-without-spark
21/09/09 15:40:06 INFO server.ZooKeeperServer: tickTime set to 3000
21/09/09 15:40:06 INFO server.ZooKeeperServer: minSessionTimeout set to -1
21/09/09 15:40:06 INFO server.ZooKeeperServer: maxSessionTimeout set to -1
21/09/09 15:40:06 INFO server.ServerCnxnFactory: Using org.apache.zookeeper.server.NIOServerCnxnFactory as server connection factory
21/09/09 15:40:06 INFO server.NIOServerCnxnFactory: binding to port 0.0.0.0/0.0.0.0:2181
21/09/09 15:40:06 ERROR test.TestingZooKeeperServer: From testing server (random state: false) for instance: InstanceSpec{dataDirectory=embedded_zookeeper, port=2181, electionPort=34991, quorumPort=33105, deleteDataDirectoryOnClose=true, serverId=1, tickTime=3000, maxClientCnxns=120, customProperties={}, hostname=127.0.0.1} org.apache.curator.test.InstanceSpec@59c3be02
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.configure(NIOServerCnxnFactory.java:90)
	at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:120)
	at org.apache.curator.test.TestingZooKeeperMain.runFromConfig(TestingZooKeeperMain.java:93)
	at org.apache.curator.test.TestingZooKeeperServer$1.run(TestingZooKeeperServer.java:148)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.configure(NIOServerCnxnFactory.java:90)
	at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:120)
	at org.apache.curator.test.TestingZooKeeperMain.runFromConfig(TestingZooKeeperMain.java:93)
	at org.apache.curator.test.TestingZooKeeperServer$1.run(TestingZooKeeperServer.java:148)
	at java.lang.Thread.run(Thread.java:748)
[root@centos4 kyuubi-1.2.0-bin-without-spark]#
```
```


### Kyuubi Engine Log Output

_No response_

### Kyuubi Server Configurations

```yaml
spark.master=spark://ip:7077
spark.executor.memory=5g
spark.sql.adaptive.enabled=true
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by timothy65535** [comment]
seems port `2181`, you can check with following command
```
netstat -tpln | grep 2181
```

**Comment by timothy65535** [comment]
or, you can specify `kyuubi.zookeeper.embedded.port`
