### ISSUE TITLE
kyuubi with  spark-authorizer report error "Permission denied: user information not available"

### ISSUE THREAD

**Issue by jiadexin** [apache/incubator-kyuubi#121]
**Describe the bug**
I  am using kyuubi with  spark-authorizer  as ACL Management ,  i can connected  kyuubi with beeline,but when i execute "select"，report error "org.apache.hadoop.hive.ql.security.authorization.plugin.HiveAccessControlException: Permission denied: user information not available"

**To Reproduce**
1. Configurations
kyubbi : refrence https://yaooqinn.github.io 
spark-authorizer : https://yaooqinn.github.io/spark-authorizer/
ranger: the hdfs user has been authorized in the ranger

2. Environments
spark-2.3.2、spark-authorizer-1.0.1.spark2.3、kyubbi 0.4.0-SNAPSHOT

3. Operations
start kyubbi : 
```
bin/start-kyuubi.sh --driver-memory 1g \
         --conf spark.kyuubi.authorization.enabled=true \
         --conf spark.kyuubi.authorization.class=org.apache.spark.sql.catalyst.optimizer.Authorizer \
         --conf spark.driver.allowMultipleContexts=true \
         --deploy-mode client
```
client connect: 
`spark-2.3.2/bin/beeline -u "jdbc:hive2://192.168.1.22:10009/;hive.server2.proxy.user=hdfs"`

```
Connecting to jdbc:hive2://192.168.1.22:10009/;hive.server2.proxy.user=hdfs
2018-11-14 10:49:42 INFO  Utils:310 - Supplied authorities: 192.168.1.22:10009
2018-11-14 10:49:42 INFO  Utils:397 - Resolved authority: 192.168.1.22:10009
2018-11-14 10:49:42 INFO  HiveConnection:203 - Will try to open client transport with JDBC Uri: jdbc:hive2://192.168.1.22:10009/;hive.server2.proxy.user=hdfs
Connected to: Spark SQL (version 2.3.2)
Driver: Hive JDBC (version 1.2.1.spark2)
Transaction isolation: TRANSACTION_REPEATABLE_READ
Beeline version 1.2.1.spark2 by Apache Hive
0: jdbc:hive2://192.168.1.22:10009/> select * from pokes;
2018-11-14 10:51:22 INFO  KyuubiOperation:33 - Running query 'select * from pokes' with 9d280cc1-12d2-4ebe-9453-ac9013067eed
2018-11-14 10:51:22 ERROR DefaultAuthorizerImpl:70 - 
+===============================+
|Spark SQL Authorization Failure |
|-------------------------------|
|Permission denied: user information not available
|-------------------------------|
|Spark SQL Authorization Failure|
+===============================+
                 
2018-11-14 10:51:22 ERROR KyuubiOperation:50 - 
Error executing query as hdfs,
select * from pokes
Current operation state RUNNING,
org.apache.hadoop.hive.ql.security.authorization.plugin.HiveAccessControlException: Permission denied: user information not available
        at org.apache.ranger.authorization.hive.authorizer.RangerHiveAuthorizer.checkPrivileges(RangerHiveAuthorizer.java:207)
        at org.apache.spark.sql.hive.DefaultAuthorizerImpl$$anonfun$checkPrivileges$1.apply(DefaultAuthorizerImpl.scala:124)
        at org.apache.spark.sql.hive.DefaultAuthorizerImpl$$anonfun$checkPrivileges$1.apply(DefaultAuthorizerImpl.scala:119)
        at scala.Option.foreach(Option.scala:257)
        at org.apache.spark.sql.hive.DefaultAuthorizerImpl.checkPrivileges(DefaultAuthorizerImpl.scala:119)
        at org.apache.spark.sql.catalyst.optimizer.Authorizer$.apply(Authorizer.scala:66)
        at org.apache.spark.sql.catalyst.optimizer.Authorizer$.apply(Authorizer.scala:42)

```

 when i debug the DefaultAuthorizerImpl code ,the username of session is null : 
![image](https://user-images.githubusercontent.com/11308161/48457898-3106b500-e7ff-11e8-954a-d85c8c1e4838.png)
![image](https://user-images.githubusercontent.com/11308161/48457916-395ef000-e7ff-11e8-9c6e-4a90df27be22.png)

and the logs file have WARN:
```
...
2018-11-14 10:39:59 INFO  KyuubiOperation:33 - Running query 'select * from pokes' with 92f5ad4a-2f8c-4284-9b6b-2b901c6f684b
2018-11-14 10:40:50 WARN  RangerHiveAuthorizerBase:70 - RangerHiveAuthorizerBase.RangerHiveAuthorizerBase(): hiveAuthenticator.getUserName() returned null/empty
2018-11-14 10:40:50 INFO  AuditProviderFactory:77 - AuditProviderFactory: creating..
...
```
### I already tested  native spark 2 thrift server+spark-authorizer , it's OK.
I don't know how to solve it,  hope you can help ,thks.

**Comment by yaooqinn** [comment]
It seems that you configured wrong authenticator manager, try to add the following to hive-site.xml
```
<!-- Ranger -->
    <property>
        <name>hive.security.authorization.enabled</name>
        <value>true</value>
    </property>
    <property>
        <name>hive.security.authorization.manager</name>
        <value>org.apache.ranger.authorization.hive.authorizer.RangerHiveAuthorizerFactory</value>
    </property>
    <property>
        <name>hive.security.authenticator.manager</name>
        <value>org.apache.hadoop.hive.ql.security.SessionStateUserAuthenticator</value>
    </property>
```

**Comment by yaooqinn** [comment]
Btw, spark-authorizer-1.0.1.spark2.3 is outdated, the latest spark-authorizer release does not bind to any spark version, it suites spark 2.1.x and later. Please use `yaooqinn/spark-authorizer:2.1.1`, then we can fix any bugs as soon as possible, thanks!

Kent
