### ISSUE TITLE
[Bug] kyuubi always report: Error operating GET_TABLES: Read a negative frame size

### ISSUE THREAD

**Issue by ethanzhou8109** [apache/incubator-kyuubi#1212]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

kyuubi always throw exception below, and after that we can't lookup table details in hue until kill kyuubi spark application and restart kyuubi 
```
org.apache.kyuubi.KyuubiSQLException: Error operating GET_TABLES: Read a negative frame size (-2147418110)!
        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:51)
        at org.apache.kyuubi.operation.KyuubiOperation$$anonfun$onError$1.applyOrElse(KyuubiOperation.scala:66)
        at org.apache.kyuubi.operation.KyuubiOperation$$anonfun$onError$1.applyOrElse(KyuubiOperation.scala:47)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
        at org.apache.kyuubi.operation.GetTables.runInternal(GetTables.scala:46)
        at org.apache.kyuubi.operation.AbstractOperation.run(AbstractOperation.scala:130)
        at org.apache.kyuubi.session.AbstractSession.runOperation(AbstractSession.scala:95)
        at org.apache.kyuubi.session.AbstractSession.getTables(AbstractSession.scala:170)
        at org.apache.kyuubi.service.AbstractBackendService.getTables(AbstractBackendService.scala:95)
        at org.apache.kyuubi.service.FrontendService.GetTables(FrontendService.scala:318)
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetTables.getResult(TCLIService.java:1517)
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetTables.getResult(TCLIService.java:1502)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
        at org.apache.kyuubi.service.authentication.HadoopThriftAuthBridgeServer$TUGIAssumingProcessor.process(HadoopThriftAuthBridgeServer.scala:163)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.transport.TTransportException: Read a negative frame size (-2147418110)!
        at org.apache.thrift.transport.TSaslTransport.readFrame(TSaslTransport.java:456)
        at org.apache.thrift.transport.TSaslTransport.read(TSaslTransport.java:435)
        at org.apache.thrift.transport.TSaslClientTransport.read(TSaslClientTransport.java:37)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
        at org.apache.hive.service.rpc.thrift.TCLIService$Client.recv_GetTables(TCLIService.java:329)
        at org.apache.hive.service.rpc.thrift.TCLIService$Client.GetTables(TCLIService.java:316)
        at org.apache.kyuubi.operation.GetTables.runInternal(GetTables.scala:43)
      ```

### Affects Version(s)

kyuubi: 1.2.0
spark: 3.1.2
hadoop: 3.0.0-cdh6.3.2

### Kyuubi Server Log Output

```logtalk
org.apache.kyuubi.KyuubiSQLException: Error operating GET_TABLES: Read a negative frame size (-2147418110)!
        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:51)
        at org.apache.kyuubi.operation.KyuubiOperation$$anonfun$onError$1.applyOrElse(KyuubiOperation.scala:66)
        at org.apache.kyuubi.operation.KyuubiOperation$$anonfun$onError$1.applyOrElse(KyuubiOperation.scala:47)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
        at org.apache.kyuubi.operation.GetTables.runInternal(GetTables.scala:46)
        at org.apache.kyuubi.operation.AbstractOperation.run(AbstractOperation.scala:130)
        at org.apache.kyuubi.session.AbstractSession.runOperation(AbstractSession.scala:95)
        at org.apache.kyuubi.session.AbstractSession.getTables(AbstractSession.scala:170)
        at org.apache.kyuubi.service.AbstractBackendService.getTables(AbstractBackendService.scala:95)
        at org.apache.kyuubi.service.FrontendService.GetTables(FrontendService.scala:318)
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetTables.getResult(TCLIService.java:1517)
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetTables.getResult(TCLIService.java:1502)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
        at org.apache.kyuubi.service.authentication.HadoopThriftAuthBridgeServer$TUGIAssumingProcessor.process(HadoopThriftAuthBridgeServer.scala:163)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.transport.TTransportException: Read a negative frame size (-2147418110)!
        at org.apache.thrift.transport.TSaslTransport.readFrame(TSaslTransport.java:456)
        at org.apache.thrift.transport.TSaslTransport.read(TSaslTransport.java:435)
        at org.apache.thrift.transport.TSaslClientTransport.read(TSaslClientTransport.java:37)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
        at org.apache.hive.service.rpc.thrift.TCLIService$Client.recv_GetTables(TCLIService.java:329)
        at org.apache.hive.service.rpc.thrift.TCLIService$Client.GetTables(TCLIService.java:316)
        at org.apache.kyuubi.operation.GetTables.runInternal(GetTables.scala:43)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by aquib14193** [comment]
We are getting this issue in higher version as well.
kyuubi version -> 1.7.0
spark Sql version -> 3.3.0

**Comment by pan3793** [comment]
@aquib14193 open a new issue with the full error stack and other information.
