### ISSUE TITLE
[Bug] The newly added kyuubi-hive-jdbc-shaded module causes the generation of the settings file and functions file to fail.

### ISSUE THREAD

**Issue by wForget** [apache/incubator-kyuubi#1267]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

The newly added kyuubi-hive-jdbc-shaded module causes the generation of the settings file and function file to fail. Do we need to modify the comments of the related classes?

command: 
`KYUUBI_UPDATE=1 build/mvn test -DwildcardSuites=org.apache.kyuubi.engine.spark.udf.KyuubiDefinedFunctionSuite -pl '!externals/kyuubi-download'`

error:

![image](https://user-images.githubusercontent.com/17894939/138073980-980130d0-2d44-4d96-ae06-225b23a58279.png)

should be changed to: 
`KYUUBI_UPDATE=1 build/mvn test -DwildcardSuites=org.apache.kyuubi.config.AllKyuubiConfiguration -pl '!externals/kyuubi-download,!kyuubi-hive-jdbc-shaded'`

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
Would you like to send a PR to update the comments?

**Comment by pan3793** [comment]
```
KYUUBI_UPDATE=1 build/mvn clean install -Pspark-provided \
  -DwildcardSuites=org.apache.kyuubi.config.AllKyuubiConfiguration
```

**Comment by wForget** [comment]
NullPointerException occurred when regenerating functions.md file. Fix in #1272 

command:
```
KYUUBI_UPDATE=1 build/mvn clean install -Pspark-provided -DwildcardSuites=org.apache.kyuubi.engine.spark.udf.KyuubiDefinedFunctionSuite
```

error:
```
KyuubiDefinedFunctionSuite:
*** RUN ABORTED ***
  java.lang.ExceptionInInitializerError:
  at org.apache.kyuubi.engine.spark.udf.KyuubiDefinedFunctionSuite.$anonfun$new$1(KyuubiDefinedFunctionSuite.scala:85)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:226)
  at org.apache.kyuubi.KyuubiFunSuite.withFixture(KyuubiFunSuite.scala:61)
  at org.apache.kyuubi.KyuubiFunSuite.withFixture$(KyuubiFunSuite.scala:55)
  ...
  Cause: java.lang.NullPointerException:
  at org.apache.kyuubi.engine.spark.udf.KDFRegistry$.<init>(KDFRegistry.scala:34)
  at org.apache.kyuubi.engine.spark.udf.KDFRegistry$.<clinit>(KDFRegistry.scala)
  at org.apache.kyuubi.engine.spark.udf.KyuubiDefinedFunctionSuite.$anonfun$new$1(KyuubiDefinedFunctionSuite.scala:85)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:226)
```
