### ISSUE TITLE
[Bug] Give a nice look for error detecting from engine log

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#1281]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

##### Before
```logtalk
Cause: java.lang.RuntimeException: org.apache.kyuubi.KyuubiSQLException:Failed to detect the root cause, please check /home/runner/work/incubator-kyuubi/incubator-kyuubi/kyuubi-server/target/work/runner/kyuubi-spark-sql-engine.log.12 at server side if necessary. The last 10 line(s) of log is: 2021-10-25 02:57:44.791 INFO session.SparkSQLSessionManager: Service[SparkSQLSessionManager] is stopped.
2021-10-25 02:57:54.792 INFO spark.SparkSQLBackendService: Service[SparkSQLBackendService] is stopped.
2021-10-25 02:57:54.792 INFO spark.SparkSQLEngine: Service[SparkSQLEngine] is stopped.
2021-10-25 02:57:54.792 INFO zookeeper.ClientCnxn: EventThread shut down for session: 0x100000ce3c00025
2021-10-25 02:57:54.793 INFO events.EventLoggingService: Service[EventLogging] is stopped.
2021-10-25 02:57:54.796 INFO storage.DiskBlockManager: Shutdown hook called
2021-10-25 02:57:54.800 INFO util.ShutdownHookManager: Shutdown hook called
2021-10-25 02:57:54.801 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-0f41791e-aad8-402d-b50d-abf5b653e4af
2021-10-25 02:57:54.807 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-198a4508-071e-4007-80b0-d5e9de9363a5
2021-10-25 02:57:54.810 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-198a4508-071e-4007-80b0-d5e9de9363a5/userFiles-3e67363d-ff2a-44bc-9350-24decb3a0100
  at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
  at org.apache.kyuubi.engine.ProcBuilder.getError(ProcBuilder.scala:193)
  at org.apache.kyuubi.engine.ProcBuilder.getError$(ProcBuilder.scala:187)
  at org.apache.kyuubi.engine.spark.SparkProcessBuilder.getError(SparkProcessBuilder.scala:35)
  at org.apache.kyuubi.engine.EngineRef.$anonfun$create$1(EngineRef.scala:204)
  at org.apache.kyuubi.engine.EngineRef.tryWithLock(EngineRef.scala:156)
  at org.apache.kyuubi.engine.EngineRef.create(EngineRef.scala:168)
  at org.apache.kyuubi.engine.EngineRef.$anonfun$getOrCreate$1(EngineRef.scala:222)
  at scala.Option.getOrElse(Option.scala:189)
  at org.apache.kyuubi.engine.EngineRef.getOrCreate(EngineRef.scala:222)
```

##### After

```logtalk
Cause: java.lang.RuntimeException: org.apache.kyuubi.KyuubiSQLException:Failed to detect the root cause, please check /home/runner/work/incubator-kyuubi/incubator-kyuubi/kyuubi-server/target/work/runner/kyuubi-spark-sql-engine.log.12 at server side if necessary. The last 10 line(s) of log are: 
  2021-10-25 02:57:44.791 INFO session.SparkSQLSessionManager: Service[SparkSQLSessionManager] is stopped.
  2021-10-25 02:57:54.792 INFO spark.SparkSQLBackendService: Service[SparkSQLBackendService] is stopped.
  2021-10-25 02:57:54.792 INFO spark.SparkSQLEngine: Service[SparkSQLEngine] is stopped.
  2021-10-25 02:57:54.792 INFO zookeeper.ClientCnxn: EventThread shut down for session: 0x100000ce3c00025
  2021-10-25 02:57:54.793 INFO events.EventLoggingService: Service[EventLogging] is stopped.
  2021-10-25 02:57:54.796 INFO storage.DiskBlockManager: Shutdown hook called
  2021-10-25 02:57:54.800 INFO util.ShutdownHookManager: Shutdown hook called
  2021-10-25 02:57:54.801 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-0f41791e-aad8-402d-b50d-abf5b653e4af
  2021-10-25 02:57:54.807 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-198a4508-071e-4007-80b0-d5e9de9363a5
  2021-10-25 02:57:54.810 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-198a4508-071e-4007- 80b0-d5e9de9363a5/userFiles-3e67363d-ff2a-44bc-9350-24decb3a0100
  at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
  at org.apache.kyuubi.engine.ProcBuilder.getError(ProcBuilder.scala:193)
  at org.apache.kyuubi.engine.ProcBuilder.getError$(ProcBuilder.scala:187)
  at org.apache.kyuubi.engine.spark.SparkProcessBuilder.getError(SparkProcessBuilder.scala:35)
  at org.apache.kyuubi.engine.EngineRef.$anonfun$create$1(EngineRef.scala:204)
  at org.apache.kyuubi.engine.EngineRef.tryWithLock(EngineRef.scala:156)
  at org.apache.kyuubi.engine.EngineRef.create(EngineRef.scala:168)
  at org.apache.kyuubi.engine.EngineRef.$anonfun$getOrCreate$1(EngineRef.scala:222)
  at scala.Option.getOrElse(Option.scala:189)
  at org.apache.kyuubi.engine.EngineRef.getOrCreate(EngineRef.scala:222)
```

### Affects Version(s)

1.4.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jadireddi** [comment]
PR for this issue: https://github.com/apache/incubator-kyuubi/pull/1316
