### ISSUE TITLE
[Bug] pyhive can't get result from kyuubi

### ISSUE THREAD

**Issue by ethan7811** [apache/incubator-kyuubi#1362]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

we use kyuubi as redash hive backend, and we use pyhive connect to kyuubi to get result, some simple sql works fine, but some complex sql always failed to get result, but in kyuubi log it seem that sql job has finished, it always throws exception as below in process of computation as below in engine log
```
21/11/11 18:05:29 ERROR scheduler.AsyncEventQueue: Listener SparkSQLEngineListener threw an exception
java.lang.NullPointerException
        at org.apache.kyuubi.engine.spark.monitor.KyuubiStatementMonitor$.$anonfun$insertJobEndTimeAndResult$2(KyuubiStatementMonitor.scala:133)
        at org.apache.kyuubi.Logging.warn(Logging.scala:60)
        at org.apache.kyuubi.Logging.warn$(Logging.scala:58)
        at org.apache.kyuubi.engine.spark.monitor.KyuubiStatementMonitor$.warn(KyuubiStatementMonitor.scala:28)
        at org.apache.kyuubi.engine.spark.monitor.KyuubiStatementMonitor$.insertJobEndTimeAndResult(KyuubiStatementMonitor.scala:133)
        at org.apache.spark.kyuubi.SparkSQLEngineListener.onJobEnd(SparkSQLEngineListener.scala:79)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:39)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
        at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
        at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
        at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
        at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1381)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
```

the exception above doesn't interrupt job execution and we finally get log like
```
21/11/11 18:05:52 INFO operation.ExecuteStatement: Processing xxx's query[f512caa2-0d60-48d1-91f8-f4b3a06c5ee6]: RUNNING_STATE -> FINISHED_STATE, statement --
xxxxxx, time taken: 44.383 seconds
21/11/11 18:06:08 INFO service.ThriftFrontendService: Received request of closing SessionHandle [2ad135fe-a481-45e7-a626-76f0fbbea931]
21/11/11 18:06:08 INFO session.SparkSQLSessionManager: SessionHandle [2ad135fe-a481-45e7-a626-76f0fbbea931] is closed, current opening sessions 0
21/11/11 18:06:08 INFO service.ThriftFrontendService: Finished closing SessionHandle [2ad135fe-a481-45e7-a626-76f0fbbea931]
21/11/11 18:06:08 ERROR server.TThreadPoolServer: Thrift error occurred during processing of message.
org.apache.thrift.transport.TTransportException
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.transport.TSaslTransport.readLength(TSaslTransport.java:374)
        at org.apache.thrift.transport.TSaslTransport.readFrame(TSaslTransport.java:451)
        at org.apache.thrift.transport.TSaslTransport.read(TSaslTransport.java:433)
        at org.apache.thrift.transport.TSaslServerTransport.read(TSaslServerTransport.java:43)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:425)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:321)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:225)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:27)
        at org.apache.kyuubi.service.authentication.TSetIpAddressProcessor.process(TSetIpAddressProcessor.scala:36)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:310)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
and redash show that "Error running query: failed communicating with server. Please check your Internet connection and try again." and logs says it's worker timeout

### Affects Version(s)

kyuubi: 1.3.0
spark: 3.1.2
hadoop: 3.0.0

### Kyuubi Server Log Output
```
21/11/12 14:36:32 INFO log.OperationLog: Creating operation log file /opt/kyuubi/apache-kyuubi-1.3.0-incubating-bin/operation_logs/cd8b33e5-c072-4c62-a81e-6f90d83c5de1/2db76511-57fe-4582-b1c8-07773e647450
21/11/12 14:36:32 INFO operation.ExecuteStatement: Processing xxx's query[2db76511-57fe-4582-b1c8-07773e647450]: INITIALIZED_STATE -> PENDING_STATE, statement: --   xxxx
21/11/12 14:36:32 INFO operation.ExecuteStatement: Processing  xxx's query[2db76511-57fe-4582-b1c8-07773e647450]: PENDING_STATE -> RUNNING_STATE, statement: --   xxx
21/11/12 14:36:37 INFO operation.ExecuteStatement: Query[2db76511-57fe-4582-b1c8-07773e647450] in RUNNING_STATE
21/11/12 14:36:42 INFO operation.ExecuteStatement: Query[2db76511-57fe-4582-b1c8-07773e647450] in RUNNING_STATE
21/11/12 14:36:47 INFO operation.ExecuteStatement: Query[2db76511-57fe-4582-b1c8-07773e647450] in RUNNING_STATE
21/11/12 14:36:52 INFO operation.ExecuteStatement: Query[2db76511-57fe-4582-b1c8-07773e647450] in RUNNING_STATE
21/11/12 14:36:57 INFO operation.ExecuteStatement: Query[2db76511-57fe-4582-b1c8-07773e647450] in RUNNING_STATE
21/11/12 14:37:02 INFO operation.ExecuteStatement: Query[2db76511-57fe-4582-b1c8-07773e647450] in RUNNING_STATE
21/11/12 14:37:07 INFO operation.ExecuteStatement: Query[2db76511-57fe-4582-b1c8-07773e647450] in RUNNING_STATE
21/11/12 14:37:12 INFO operation.ExecuteStatement: Query[2db76511-57fe-4582-b1c8-07773e647450] in RUNNING_STATE
21/11/12 14:37:13 INFO operation.ExecuteStatement: Query[2db76511-57fe-4582-b1c8-07773e647450] in FINISHED_STATE
21/11/12 14:37:13 INFO operation.ExecuteStatement: Processing  xxx's query[2db76511-57fe-4582-b1c8-07773e647450]: RUNNING_STATE -> FINISHED_STATE, statement: --   xxxx
21/11/12 14:37:31 INFO operation.ExecuteStatement: Processing  xxx's query[2db76511-57fe-4582-b1c8-07773e647450]: FINISHED_STATE -> CLOSED_STATE, statement: --   xxxx
```

_No response_

### Kyuubi Server Configurations
```
kyuubi.authentication=KERBEROS
kyuubi.frontend.bind.host=xxxx
kyuubi.frontend.bind.port=10003
kyuubi.ha.enabled=true
kyuubi.ha.zookeeper.acl.enabled=false
kyuubi.ha.zookeeper.client.port=2181
kyuubi.ha.zookeeper.namespace=kyuubi-ha
kyuubi.ha.zookeeper.quorum=xxxx
kyuubi.kinit.keytab=/etc/keytabs/hive.keytab
kyuubi.kinit.principal=xxxxx
kyuubi.session.engine.login.timeout=PT30M
kyuubi.session.idle.timeout=PT30M
kyuubi.operation.idle.timeout=PT1H
```

### Kyuubi Engine Configurations
```
spark.driver.maxResultSize=1g
spark.driver.memory=2g
spark.dynamicAllocation.maxExecutors=10
spark.executor.cores=3
spark.executor.memory=12G
spark.submit.deployMode=client
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
https://github.com/apache/incubator-kyuubi/commit/5421b56440cdd0d07de0a98d5a3dc0cfb9ef312e seem to be fixed by this

**Comment by ethan7811** [comment]
> [5421b56](https://github.com/apache/incubator-kyuubi/commit/5421b56440cdd0d07de0a98d5a3dc0cfb9ef312e) seem to be fixed by this

why increase "kyuubi.session.engine.login.timeout" seems not work, and is NPE throw by SparkSQLEngineListener matter?

**Comment by yaooqinn** [comment]
> why increase "kyuubi.session.engine.login.timeout" seems not work

pyhive uses a very low TProtocalVersion of hive-rpc, we didn't handle it right for running query synchronously.

> does the NPE throw by SparkSQLEngineListener matter？

IIUC, it doesn't hurt the main execution logic. 
KyuubiStatementMonitor has been removed completely in the master branch. cc @zhang1002 as the original author of this feature too.

**Comment by pan3793** [comment]
> why increase "kyuubi.session.engine.login.timeout" seems not work

If it's the issue about 5421b56, increase "kyuubi.session.engine.login.timeout" should work.

> some simple sql works fine, but some complex sql always failed to get result

@ethan7811 to identity if it's affect by query time, would you please try `select java_method('java.lang.Thread', 'sleep', 10000L)` to simulate **complex** query?

**Comment by pan3793** [comment]
BTW, does Redash support async mode? if yes, trun on it and see what happens

**Comment by ethan7811** [comment]
> BTW, does Redash support async mode? if yes, trun on it and see what happens

we try pyhive async mode in redash and it doesn't work, same errors as above

**Comment by ethan7811** [comment]
> select java_method('java.lang.Thread', 'sleep', 10000L)

```select java_method('java.lang.Thread', 'sleep', 10000L)``` this query seems works fine

**Comment by pan3793** [comment]
What if increse the sleep time?

**Comment by ethan7811** [comment]
> What if increse the sleep time?

we changed to 100000L  and it works too

**Comment by yaooqinn** [comment]
Maybe https://github.com/apache/incubator-kyuubi/commit/fd17dd0ae429cc62b45ae705b362cb80d6015407 is also related. If so `spark.driver.memory=2g` is too small for your complex queries. 

Can you try the master branch?

**Comment by ethan7811** [comment]
> Maybe [fd17dd0](https://github.com/apache/incubator-kyuubi/commit/fd17dd0ae429cc62b45ae705b362cb80d6015407) is also related. If so `spark.driver.memory=2g` is too small for your complex queries.
> 
> Can you try the master branch?

finally we find that its because redash worker has been dead, and we limit smaller query result and it seems work, it should not be kyuubi's problem, sorry for disturbing

**Comment by yaooqinn** [comment]
Can you share a use case at #925 if appropriate?
