### ISSUE TITLE
[FEATURE] Make KYUUBI_WORK_DIR_ROOT as the default root path.

### ISSUE THREAD

**Issue by wForget** [apache/incubator-kyuubi#1509]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

The `METRICS_JSON_LOCATION` and `SERVER_OPERATION_LOG_DIR_ROOT` paths are relative to `user.dir` by default.
I got an error during startup and I want to change it to a path relative to `KYUUBI_WORK_DIR_ROOT`.

command:
```
cd /
sudo -u user ${KYUUBI_HOME}/bin/kyuubi start
```

error:
```
Exception in thread "main" java.nio.file.AccessDeniedException: /metrics
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at org.apache.kyuubi.metrics.JsonReporterService.initialize(JsonReporterService.scala:47)
	at org.apache.kyuubi.service.CompositeService.$anonfun$initialize$1(CompositeService.scala:40)
	at org.apache.kyuubi.service.CompositeService.$anonfun$initialize$1$adapted(CompositeService.scala:40)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.kyuubi.service.CompositeService.initialize(CompositeService.scala:40)
	at org.apache.kyuubi.metrics.MetricsSystem.initialize(MetricsSystem.scala:66)
	at org.apache.kyuubi.service.CompositeService.$anonfun$initialize$1(CompositeService.scala:40)
	at org.apache.kyuubi.service.CompositeService.$anonfun$initialize$1$adapted(CompositeService.scala:40)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.kyuubi.service.CompositeService.initialize(CompositeService.scala:40)
	at org.apache.kyuubi.service.Serverable.initialize(Serverable.scala:46)
	at org.apache.kyuubi.server.KyuubiServer.initialize(KyuubiServer.scala:154)
	at org.apache.kyuubi.server.KyuubiServer$.startServer(KyuubiServer.scala:92)
	at org.apache.kyuubi.server.KyuubiServer$.main(KyuubiServer.scala:121)
	at org.apache.kyuubi.server.KyuubiServer.main(KyuubiServer.scala)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
👍

**Comment by wForget** [comment]
After modification, the `METRICS_JSON_LOCATION` and `SERVER_OPERATION_LOG_DIR_ROOT` paths are relative to `KYUUBI_WORK_DIR_ROOT`
![2](https://user-images.githubusercontent.com/17894939/144976289-4f19f19d-21bc-4cda-b95f-6305889ea186.png)

the `ENGINE_OPERATION_LOG_DIR_ROOT` path relative to `user.dir`
![1](https://user-images.githubusercontent.com/17894939/144976508-6c2a5700-de20-4ddb-b6d1-68c50be7281b.png)
