### ISSUE TITLE
[Bug] The killApplication method doesn't seem to be working properly

### ISSUE THREAD

**Issue by wForget** [apache/incubator-kyuubi#1794]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

The killApplication method doesn't seem to be working properly.

![20220118161731](https://user-images.githubusercontent.com/17894939/149897701-47696093-8524-4228-88dd-1aaaf3ab6219.png)

### Affects Version(s)

1.4.0

### Kyuubi Server Log Output

```logtalk
Failed to kill Application application_1639106513453_1048001, please kill it manually. 
        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
        at org.apache.kyuubi.session.KyuubiSessionManager.openSession(KyuubiSessionManager.scala:82)
        at org.apache.kyuubi.service.AbstractBackendService.openSession(AbstractBackendService.scala:45)
        at org.apache.kyuubi.service.ThriftBinaryFrontendService.getSessionHandle(ThriftBinaryFrontendService.scala:199)
        at org.apache.kyuubi.server.KyuubiThriftBinaryFrontendService.OpenSession(KyuubiThriftBinaryFrontendService.scala:46)
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$OpenSession.getResult(TCLIService.java:1377)
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$OpenSession.getResult(TCLIService.java:1362)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
        at org.apache.kyuubi.service.authentication.HadoopThriftAuthBridgeServer$TUGIAssumingProcessor.process(HadoopThriftAuthBridgeServer.scala:162)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: org.apache.kyuubi.KyuubiSQLException: Timeout(180000 ms) to launched SPARK_SQL engine with
```

### Kyuubi Engine Log Output

```logtalk
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Error occurred during initialization of VM
java.lang.Error: Properties init: Could not determine current working directory.
	at java.lang.System.initProperties(Native Method)
	at java.lang.System.initializeSystemClass(System.java:1166)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wForget** [comment]
I guess it may be necessary to call the java.lang.ProcessBuilder#directory(java.io.File) method to set the work dir.

**Comment by yaooqinn** [comment]
thanks for reporting this bug

**Comment by wForget** [comment]
It occurs when I redeploy the kyuubi dist package without restarting the service.

**Comment by cxzl25** [comment]
Since we use the api method to kill yarn app (https://github.com/apache/incubator-kyuubi/issues/2104), this bug started by process should not appear?

**Comment by wForget** [comment]
> Since we use the api method to kill yarn app (#2104), this bug started by process should not appear?

you are right, i will close this.
