### ISSUE TITLE
[Bug] When the Spark application fails to submit, the session still waits for the timeout to exit

### ISSUE THREAD

**Issue by wForget** [apache/incubator-kyuubi#1796]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Because `spark.yarn.submit.waitAppCompletion=false` is configured, the spark submit process exits normally before the spark application completes, so when the spark application fails, the session still waits for a timeout to exit.

### Affects Version(s)

master

### Kyuubi Server Log Output

```logtalk
2022-01-19 08:50:01,593 ERROR [KyuubiThriftBinaryFrontendServiceHandler-Pool: Thread-13751]: org.apache.kyuubi.server.KyuubiThriftBinaryFrontendService(72) - Error opening session: 
org.apache.kyuubi.KyuubiSQLException: Error opening session for cupid_dp client ip *.*.*.*, due to org.apache.kyuubi.KyuubiSQLException: Timeout(43200000 ms) to launched SPARK_SQL engine with /*/bin/spark-submit \
        --class org.apache.kyuubi.engine.spark.SparkSQLEngine \
        --conf spark.kyuubi.session.engine.initialize.timeout=43200000 \
......
```

### Kyuubi Engine Log Output

```logtalk
22/01/18 20:51:59 ERROR ApplicationMaster: Uncaught exception: 
java.util.concurrent.TimeoutException: Futures timed out after [100000 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:293)
	at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:504)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:268)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:899)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:898)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1762)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:898)
	at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
22/01/18 20:51:59 INFO ApplicationMaster: Final app status: FAILED, exitCode: 13, (reason: Uncaught exception: java.util.concurrent.TimeoutException: Futures timed out after [100000 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:293)
	at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:504)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:268)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:899)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:898)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1762)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:898)
	at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
```

### Kyuubi Server Configurations

```yaml
kyuubi.session.engine.initialize.timeout 43200000
spark.yarn.submit.waitAppCompletion false
```

### Additional context

Thanks to @turboFei and @ulysses-you for their suggestions, there are two ways:
1. Remove the `spark.yarn.submit.waitAppCompletion=false` configuration and call `process.destroyForcibly()` in `org.apache.kyuubi.engine.ProcBuilder#close` to end the spark submit process. (The process cannot be destroyed in client mode)
2. When the spark submit process is submitted normally, add a shell script to judge the spark application status.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by wForget** [comment]
cc @turboFei  @ulysses-you  @yaooqinn , which way is better?

**Comment by ulysses-you** [comment]
In general the value of `kyuubi.session.engine.initialize.timeout` should be 5mins or even less. why it's so big ?

**Comment by wForget** [comment]
> In general the value of `kyuubi.session.engine.initialize.timeout` should be 5mins or even less. why it's so big ?

In the early morning, the yarn queue is full. For the scheduled batch job, I hope it can wait for resources for a long time.

**Comment by yaooqinn** [comment]
seem that our main method had been invoked, maybe we can build an extra RPC layer for engine to report its starting statuses to the server that launches it

**Comment by wForget** [comment]
> seem that our main method had been invoked, maybe we can build an extra RPC layer for engine to report its starting statuses to the server that launches it

It may also fail before the mian method is invoked.
```
2022-01-17 06:26:59,603 WARN [ContainerLocalizer Downloader] org.apache.hadoop.hdfs.client.impl.BlockReaderFactory: I/O error constructing remote block reader.
java.io.IOException: DestHost:destPort XX.XX.XX:8888 , LocalHost:localPort XX.XX.XX/XX.XX.XX:0. Failed on local exception: java.io.IOException: java.io.InterruptedIOException: Interrupted while waiting for IO on channel java.nio.channels.SocketChannel[connected local=/XX.XX.XX:45616 remote=XX.XX.XX/XX.XX.XX:8888]. Total timeout mills is 120000, 117866 millis timeout left.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:856)
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:831)
        at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1566)
        at org.apache.hadoop.ipc.Client.call(Client.java:1508)
        at org.apache.hadoop.ipc.Client.call(Client.java:1405)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:233)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:118)
        at com.sun.proxy.$Proxy10.getServerDefaults(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getServerDefaults(ClientNamenodeProtocolTranslatorPB.java:341)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
        at com.sun.proxy.$Proxy11.getServerDefaults(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.getServerDefaults(DFSClient.java:673)
        at org.apache.hadoop.hdfs.DFSClient.shouldEncryptData(DFSClient.java:1768)
        at org.apache.hadoop.hdfs.DFSClient.newDataEncryptionKey(DFSClient.java:1774)
        at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferClient.checkTrustAndSend(SaslDataTransferClient.java:244)
        at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferClient.checkTrustAndSend(SaslDataTransferClient.java:227)
        at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferClient.peerSend(SaslDataTransferClient.java:170)
        at org.apache.hadoop.hdfs.DFSUtilClient.peerFromSocketAndKey(DFSUtilClient.java:731)
        at org.apache.hadoop.hdfs.DFSClient.newConnectedPeer(DFSClient.java:2976)
        at org.apache.hadoop.hdfs.client.impl.BlockReaderFactory.nextTcpPeer(BlockReaderFactory.java:823)
        at org.apache.hadoop.hdfs.client.impl.BlockReaderFactory.getRemoteBlockReaderFromTcp(BlockReaderFactory.java:748)
        at org.apache.hadoop.hdfs.client.impl.BlockReaderFactory.build(BlockReaderFactory.java:381)
        at org.apache.hadoop.hdfs.DFSInputStream.getBlockReader(DFSInputStream.java:735)
        at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:666)
        at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:851)
        at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:923)
        at java.io.DataInputStream.read(DataInputStream.java:149)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at java.io.PushbackInputStream.read(PushbackInputStream.java:186)
        at java.util.zip.ZipInputStream.readFully(ZipInputStream.java:403)
        at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:278)
        at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:122)
        at org.apache.hadoop.fs.FileUtil.unZip(FileUtil.java:632)
        at org.apache.hadoop.yarn.util.FSDownload.unpack(FSDownload.java:339)
        at org.apache.hadoop.yarn.util.FSDownload.downloadAndUnpack(FSDownload.java:307)
        at org.apache.hadoop.yarn.util.FSDownload.verifyAndCopy(FSDownload.java:287)
        at org.apache.hadoop.yarn.util.FSDownload.access$000(FSDownload.java:68)
        at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:418)
        at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:415)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1762)
        at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:415)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.doDownloadCall(ContainerLocalizer.java:246)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.call(ContainerLocalizer.java:239)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.call(ContainerLocalizer.java:227)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.io.InterruptedIOException: Interrupted while waiting for IO on channel java.nio.channels.SocketChannel[connected local=/XX.XX.XX:45616 remote=XX.XX.XX/XX.XX.XX:8888]. Total timeout mills is 120000, 117866 millis timeout left.
        at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:778)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1762)
        at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:732)
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:835)
        at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:413)
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1636)
        at org.apache.hadoop.ipc.Client.call(Client.java:1452)
        ... 56 more
Caused by: java.io.InterruptedIOException: Interrupted while waiting for IO on channel java.nio.channels.SocketChannel[connected local=/XX.XX.XX:45616 remote=XX.XX.XX/XX.XX.XX:8888]. Total timeout mills is 120000, 117866 millis timeout left.
        at org.apache.hadoop.net.SocketIOWithTimeout$SelectorPool.select(SocketIOWithTimeout.java:351)
        at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:157)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at java.io.DataInputStream.readInt(DataInputStream.java:387)
        at org.apache.hadoop.ipc.Client$IpcStreams.readResponse(Client.java:1880)
        at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:365)
        at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:622)
        at org.apache.hadoop.ipc.Client$Connection.access$2300(Client.java:413)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:822)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:818)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1762)
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:818)
        ... 59 more
```

**Comment by yaooqinn** [comment]
> Remove the spark.yarn.submit.waitAppCompletion=false configuration and call process.destroyForcibly() in org.apache.kyuubi.engine.ProcBuilder#close to end the spark submit process. (The process cannot be destroyed in client mode)

We rely on client/driver log heavily, so I agree we shouldn't allow `spark.yarn.submit.waitAppCompletion=false` for better error detecting.

I prefer 1 to 2 in general. Are we able to check the process is free to call `process.destroyForcibly()`?

**Comment by wForget** [comment]
> Are we able to check the process is free to call `process.destroyForcibly()`?

Thanks @yaooqinn , do you have any suggestions? I didn't think of a good way to check it. Maybe we can add a configuration to control.

**Comment by yaooqinn** [comment]
Me either for now.

If you have time, you can prepare the PR for adding a conf to control.

Let's also give us a couple of days to investigate if there is an any better option.

**Comment by turboFei** [comment]
I had merged this pr and tested it on our test env.

It seems that it does not work.


I have to found another temporary workaround.

```
  protected val KYUUBI_PROC_UNIQUE_ID: String = "kyuubi.proc.uniqueId"

  protected lazy val procUniqueId = UUID.randomUUID().toString

  protected def procConf(): Map[String, String] = Map(KYUUBI_PROC_UNIQUE_ID -> procUniqueId)
```

```
    var allConf = conf.getAll ++ procConf()
```


```
  protected def killProcessByUniqueId(): Unit = {
    val psEf = Runtime.getRuntime.exec("ps -ef")
    val input = new BufferedReader(new InputStreamReader(psEf.getInputStream))
    val regex = s"$KYUUBI_PROC_UNIQUE_ID=$procUniqueId".r
    var psInfo = input.readLine()
    var found = false
    while (!found && psInfo != null) {
      regex findFirstIn (psInfo) match {
        case Some(_) =>
          found = true
          psInfo.trim.split("\\s+").drop(1).headOption.foreach { psId =>
            Runtime.getRuntime.exec(s"kill -9 $psId")
          }
        case None =>
      }
      psInfo = input.readLine()
    }
  }

```

**Comment by turboFei** [comment]
https://stackoverflow.com/questions/24002366/destroy-not-working-in-java/24002483

I am not sure whether it is a bug of jdk.

I tested it both on jdk8 and jdk11, they does not work.

So, I have to use above workaround to cleanup the submit process.

**Comment by wForget** [comment]
@turboFei , It works fine on our online, the kyuubi version is 1.4.0 and java version is '1.8.0_131'. Are there any error logs?
