### ISSUE TITLE
[Bug] Exit spark engine if spark context is stopped

### ISSUE THREAD

**Issue by ulysses-you** [apache/incubator-kyuubi#1800]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

If the spark engine get OOM issue or underlying bug, the SparkContext will stop itself. However the engine jvm is still alived and it become a zombie process.

We should aware the status of SparkContext and stop the spark engine if it's already stopped.

The error msg:
```

(No active SparkContext.)

        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:73)
        at org.apache.kyuubi.engine.spark.session.SparkSQLSessionManager.openSession(SparkSQLSessionManager.scala:93)
        at org.apache.kyuubi.service.AbstractBackendService.openSession(AbstractBackendService.scala:45)
        at org.apache.kyuubi.service.ThriftBinaryFrontendService.getSessionHandle(ThriftBinaryFrontendService.scala:199)
        at org.apache.kyuubi.service.ThriftBinaryFrontendService.OpenSession(ThriftBinaryFrontendService.scala:208)
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$OpenSession.getResult(TCLIService.java:1497)
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$OpenSession.getResult(TCLIService.java:1482)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
        at org.apache.kyuubi.service.authentication.TSetIpAddressProcessor.process(TSetIpAddressProcessor.scala:36)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:310)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
```

### Affects Version(s)

1.3.1/1.4.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
have you checked the jstack to see which thread blocked termination?

BTW, we seem to have a listener to handle it

```scala
  override def onApplicationEnd(event: SparkListenerApplicationEnd): Unit = {
    server.getServiceState match {
      case ServiceState.STOPPED =>
        debug("Received ApplicationEnd Message form Spark after the engine has stopped")
      case state =>
        info(s"Received ApplicationEnd Message from Spark at $state, stopping")
        server.stop()
    }
  }
```

**Comment by wForget** [comment]
> BTW, we seem to have a listener to handle it

We can't seem to handle the SparkListenerApplicationEnd event since the listenerbus dispatch thread has stopped.

```
22/06/09 13:46:35 ERROR Utils: uncaught error in thread spark-listener-group-appStatus, stopping SparkContext
java.lang.OutOfMemoryError: GC overhead limit exceeded
.....
22/06/09 13:49:36 ERROR Utils: uncaught error in thread spark-listener-group-shared, stopping SparkContext
java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by ulysses-you** [comment]
I think the issue is that:
The SparkContext is goind to stop and send SparkListenerApplicationEnd to listener, but due to the GC overhead the work thread has no chance to actually do dispatch the event.

One option to solve this issue is: we can add an OutOfMemoryError hook at spark driver java options to do kill since we have removed the internal OutOfMemoryError hook.
