### ISSUE TITLE
[Bug] Unexpected Zk lock failure when launching engine

### ISSUE THREAD

**Issue by shenbinglife** [apache/incubator-kyuubi#1894]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug
```
2022-02-11 14:10:10,756 ERROR [KyuubiThriftBinaryFrontendServiceHandler-Pool: Thread-46] org.apache.kyuubi.Logging:72  - Error executing statement:
java.util.concurrent.ExecutionException: org.apache.kyuubi.KyuubiSQLException: Lock failed on path [/kyuubi_USER/lock/bi_jiangj/default]
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$waitForEngineLaunched$1(KyuubiSessionImpl.scala:123)
        at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$waitForEngineLaunched$1$adapted(KyuubiSessionImpl.scala:119)
        at scala.Option.foreach(Option.scala:407)
        at org.apache.kyuubi.session.KyuubiSessionImpl.waitForEngineLaunched(KyuubiSessionImpl.scala:119)
        at org.apache.kyuubi.session.KyuubiSessionImpl.runOperation(KyuubiSessionImpl.scala:109)
        at org.apache.kyuubi.session.AbstractSession.$anonfun$executeStatement$1(AbstractSession.scala:121)
        at org.apache.kyuubi.session.AbstractSession.withAcquireRelease(AbstractSession.scala:75)
        at org.apache.kyuubi.session.AbstractSession.executeStatement(AbstractSession.scala:118)
        at org.apache.kyuubi.service.AbstractBackendService.executeStatement(AbstractBackendService.scala:61)
        at org.apache.kyuubi.server.KyuubiServer$$anon$1.org$apache$kyuubi$server$BackendServiceTimeMetric$$super$executeStatement(KyuubiServer.scala:144)
        at org.apache.kyuubi.server.BackendServiceTimeMetric.$anonfun$executeStatement$1(BackendServiceTimeMetric.scala:72)
        at org.apache.kyuubi.server.BackendServiceTimeMetric.timeMetric(BackendServiceTimeMetric.scala:34)
        at org.apache.kyuubi.server.BackendServiceTimeMetric.executeStatement(BackendServiceTimeMetric.scala:72)
        at org.apache.kyuubi.server.BackendServiceTimeMetric.executeStatement$(BackendServiceTimeMetric.scala:66)
        at org.apache.kyuubi.server.KyuubiServer$$anon$1.executeStatement(KyuubiServer.scala:144)
        at org.apache.kyuubi.service.ThriftBinaryFrontendService.ExecuteStatement(ThriftBinaryFrontendService.scala:266)
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1437)
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1422)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
        at org.apache.kyuubi.service.authentication.TSetIpAddressProcessor.process(TSetIpAddressProcessor.scala:36)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kyuubi.KyuubiSQLException: Lock failed on path [/kyuubi_USER/lock/bi_jiangj/default]
        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
        at org.apache.kyuubi.engine.EngineRef.tryWithLock(EngineRef.scala:157)
        at org.apache.kyuubi.engine.EngineRef.create(EngineRef.scala:173)
        at org.apache.kyuubi.engine.EngineRef.$anonfun$getOrCreate$1(EngineRef.scala:246)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.kyuubi.engine.EngineRef.getOrCreate(EngineRef.scala:246)
        at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1(KyuubiSessionImpl.scala:95)
        at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1$adapted(KyuubiSessionImpl.scala:94)
        at org.apache.kyuubi.ha.client.ZooKeeperClientProvider$.withZkClient(ZooKeeperClientProvider.scala:81)
        at org.apache.kyuubi.ha.client.ZooKeeperClientProvider$.withZkClient(ZooKeeperClientProvider.scala:81)
        at org.apache.kyuubi.session.KyuubiSessionImpl.openEngineSession(KyuubiSessionImpl.scala:94)
        at org.apache.kyuubi.operation.LaunchEngine.$anonfun$runInternal$1(LaunchEngine.scala:51)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more
Caused by: java.lang.NullPointerException
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:94)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:792)
        at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:740)
        at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:723)
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
        at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:720)
        at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:484)
        at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:474)
        at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:454)
        at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:44)
        at org.apache.curator.framework.recipes.locks.StandardLockInternalsDriver.createsTheLock(StandardLockInternalsDriver.java:54)
        at org.apache.curator.framework.recipes.locks.LockInternals.attemptLock(LockInternals.java:217)
        at org.apache.curator.framework.recipes.locks.InterProcessMutex.internalLock(InterProcessMutex.java:232)
        at org.apache.curator.framework.recipes.locks.InterProcessMutex.acquire(InterProcessMutex.java:108)
        at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreV2.internalAcquire1Lease(InterProcessSemaphoreV2.java:344)
        at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreV2.acquire(InterProcessSemaphoreV2.java:284)
        at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreV2.acquire(InterProcessSemaphoreV2.java:246)
        at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreMutex.acquire(InterProcessSemaphoreMutex.java:52)
        at org.apache.kyuubi.engine.EngineRef.tryWithLock(EngineRef.scala:155)
```

### Affects Version(s)

1.5.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
> java.lang.NullPointerException
the NPE occurred at `org.apache.zookeeper.KeeperException create(Code code)` where the `code` here is null.

So I guess you got conflict jars or incompatible jars for zookeeper or curator?

**Comment by pan3793** [comment]
@shenbinglife which version of your zk server? do you have any modification of kyuubi server?

**Comment by shenbinglife** [comment]
zookeeper jar 3.4.14, zookeeper server 3.5.x

**Comment by pan3793** [comment]
Not sure if related https://github.com/apache/zookeeper/pull/1764, we choose zookeeper 3.4 client because it claims to support 3.4/3.5/3.6 server, see more details at https://github.com/apache/incubator-kyuubi/issues/838. You can change the zookeeper versionin pom to align your zk server and rebuild kyuubi, maybe it helps.

**Comment by shenbinglife** [comment]
how to upgrade Zookeeper and curator in kyuubi for zookeeper server 3.5.6 ？ 
when I change zk version and curator to 3.5.6 and 5.2.0, ACLProvider has problems， and what's dev/dependencyList  file used for?

**Comment by pan3793** [comment]
You can upgrade ZK only, and keep using Curator 2.x

**Comment by shenbinglife** [comment]
compile failed how to resolve it? 

```java
[INFO] --- scala-maven-plugin:4.5.6:compile (scala-compile-first) @ kyuubi-metrics_2.12 ---
[INFO] Using incremental compilation using Mixed compile order
[INFO] Compiler bridge file: C:\Users\shenb\.sbt\1.0\zinc\org.scala-sbt\org.scala-sbt-compiler-bridge_2.12-1.5.8-bin_2.12.15__52.0-1.5.8_20211211T222914.jar
[INFO] compiler plugin: BasicArtifact(com.github.ghik,silencer-plugin_2.12.15,1.7.6,null)
[INFO] compiling 10 Scala sources to D:\workspace\github\kyuubi\kyuubi-metrics\target\scala-2.12\classes ...
[ERROR] D:/workspace/github/kyuubi/kyuubi-ha/src/main/scala/org/apache/kyuubi/ha/client/zookeeper/ServiceDiscoveryClient.scala:106: Class org.apache.zookeeper.data.Stat not found - continuing with a stub.
[ERROR] one error found
[INFO] done compiling
[INFO] compile in 3.9 s

```

**Comment by pan3793** [comment]
Answered in https://github.com/apache/incubator-kyuubi/pull/1918#issuecomment-1046536297

**Comment by pan3793** [comment]
@shenbinglife before upgrading the zk client, have you checked you zk server log? do you think if it caused by https://github.com/apache/zookeeper/pull/1764?

**Comment by shenbinglife** [comment]
> @shenbinglife before upgrading the zk client, have you checked your zk server log? do you think if it caused by [apache/zookeeper#1764](https://github.com/apache/zookeeper/pull/1764)?

aggree with you
