### ISSUE TITLE
[Bug] Zookeeper 3.4 does not support JDK 17

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#1941]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Env: AArach64 JDK-17 

`EmbeddedZookeeperSuite` failed because of [ZOOKEEPER-3779](https://issues.apache.org/jira/browse/ZOOKEEPER-3779)
```
10:37:41.862 ScalaTest-main-running-EmbeddedZookeeperSuite-SendThread(10.242.138.159:38827) WARN ClientCnxn: Session 0x0 for server 10.242.138.159/<unresolved>:38827, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address 10.242.138.159/<unresolved>:38827 because it's not resolvable
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:65) ~[zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:41) ~[zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1001) ~[zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) [zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
```

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
The Zookeeper PMC member said:
> The suggestion is to switch to 3.6.2 client, it should work out-of-the-box with 3.4 servers (if you do not use new features)

https://github.com/apache/zookeeper/pull/1509#issuecomment-712398339

**Comment by pan3793** [comment]
The previous disscusion https://github.com/apache/incubator-kyuubi/issues/838

**Comment by pan3793** [comment]
An initial idea is upgrade Zookeeper to 3.5.9 and setup an IT to ensure it compatible with Zookeeper 3.4 server.

**Comment by yaooqinn** [comment]
Why not 3.6.2？

**Comment by pan3793** [comment]
link #1894
