### ISSUE TITLE
[Bug] Flink SQL connector hive no such method

### ISSUE THREAD

**Issue by cutiechi** [apache/incubator-kyuubi#2154]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug
```
➜ beeline -u 'jdbc:hive2://192.168.9.70:10009' -n admin
Connecting to jdbc:hive2://192.168.9.70:10009
18:31:20.642 INFO org.apache.kyuubi.operation.LaunchEngine: Processing admin's query[6bfe24bf-aef2-4fca-9e30-fd5e7244c452]: INITIALIZED_STATE -> PENDING_STATE, statement: LAUNCH_ENGINE
18:31:20.642 INFO org.apache.kyuubi.operation.LaunchEngine: Processing admin's query[6bfe24bf-aef2-4fca-9e30-fd5e7244c452]: PENDING_STATE -> RUNNING_STATE, statement: LAUNCH_ENGINE
18:31:20.643 INFO org.apache.curator.framework.imps.CuratorFrameworkImpl: Starting
18:31:20.643 INFO org.apache.zookeeper.ZooKeeper: Initiating client connection, connectString=192.168.9.70:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@3fbeb3ad
18:31:20.659 INFO org.apache.zookeeper.ClientCnxn: Opening socket connection to server 192.168.9.70/192.168.9.70:2181. Will not attempt to authenticate using SASL (unknown error)
18:31:20.660 INFO org.apache.zookeeper.ClientCnxn: Socket connection established to 192.168.9.70/192.168.9.70:2181, initiating session
18:31:20.679 INFO org.apache.zookeeper.ClientCnxn: Session establishment complete on server 192.168.9.70/192.168.9.70:2181, sessionid = 0x1016f433b3c0003, negotiated timeout = 60000
18:31:20.680 INFO org.apache.curator.framework.state.ConnectionStateManager: State change: CONNECTED
18:31:20.681 INFO org.apache.kyuubi.ha.client.ServiceDiscovery: Get service instance:192.168.9.70:42277 and version:Some(1.6.0-SNAPSHOT) under /kyuubi_1.6.0-SNAPSHOT_USER_FLINK_SQL/admin/default
18:31:20.697 INFO org.apache.kyuubi.session.KyuubiSessionImpl: [admin:192.168.9.70] SessionHandle [4ceb4349-149c-4339-bbf4-3dec1afa74bc] - Connected to engine [192.168.9.70:42277] with SessionHandle [2866fa93-56d0-4ae7-8548-628cdbf2557d]
18:31:20.698 INFO org.apache.curator.framework.imps.CuratorFrameworkImpl: backgroundOperationsLoop exiting
18:31:20.704 INFO org.apache.zookeeper.ZooKeeper: Session: 0x1016f433b3c0003 closed
18:31:20.704 INFO org.apache.zookeeper.ClientCnxn: EventThread shut down for session: 0x1016f433b3c0003
18:31:20.705 INFO org.apache.kyuubi.operation.LaunchEngine: Processing admin's query[6bfe24bf-aef2-4fca-9e30-fd5e7244c452]: RUNNING_STATE -> FINISHED_STATE, statement: LAUNCH_ENGINE, time taken: 0.062 seconds
Connected to: Apache Kyuubi (Incubating) (version 1.6.0-SNAPSHOT)
Driver: Kyuubi Project Hive JDBC Client (version 1.6.0-SNAPSHOT)
Beeline version 1.6.0-SNAPSHOT by Apache Kyuubi (Incubating)
0: jdbc:hive2://192.168.9.70:10009> CREATE CATALOG myhive WITH ('type' = 'hive', 'default-database' = 'mydatabase', 'hive-conf-dir' = '/home/cutiechi/applications/hive/current/conf');
18:31:22.239 INFO org.apache.kyuubi.operation.ExecuteStatement: Processing admin's query[0846c2de-c6ec-4117-825e-4454d6a9abf5]: INITIALIZED_STATE -> PENDING_STATE, statement: CREATE CATALOG myhive WITH ('type' = 'hive', 'default-database' = 'mydatabase', 'hive-conf-dir' = '/home/cutiechi/applications/hive/current/conf')
18:31:22.241 INFO org.apache.kyuubi.operation.ExecuteStatement: Processing admin's query[0846c2de-c6ec-4117-825e-4454d6a9abf5]: PENDING_STATE -> RUNNING_STATE, statement: CREATE CATALOG myhive WITH ('type' = 'hive', 'default-database' = 'mydatabase', 'hive-conf-dir' = '/home/cutiechi/applications/hive/current/conf')
18:31:22.289 INFO org.apache.kyuubi.operation.ExecuteStatement: Query[0846c2de-c6ec-4117-825e-4454d6a9abf5] in ERROR_STATE
18:31:22.289 INFO org.apache.kyuubi.operation.ExecuteStatement: Processing admin's query[0846c2de-c6ec-4117-825e-4454d6a9abf5]: RUNNING_STATE -> ERROR_STATE, statement: CREATE CATALOG myhive WITH ('type' = 'hive', 'default-database' = 'mydatabase', 'hive-conf-dir' = '/home/cutiechi/applications/hive/current/conf'), time taken: 0.048 seconds
Error: Error operating EXECUTE_STATEMENT: org.apache.flink.table.client.gateway.SqlExecutionException: Could not execute SQL statement.
        at org.apache.flink.table.client.gateway.local.LocalExecutor.executeOperation(LocalExecutor.java:211)
        at org.apache.kyuubi.engine.flink.operation.ExecuteStatement.runOperation(ExecuteStatement.scala:171)
        at org.apache.kyuubi.engine.flink.operation.ExecuteStatement.org$apache$kyuubi$engine$flink$operation$ExecuteStatement$$executeStatement(ExecuteStatement.scala:119)
        at org.apache.kyuubi.engine.flink.operation.ExecuteStatement$$anon$1.run(ExecuteStatement.scala:78)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.flink.table.api.ValidationException: Could not execute CREATE CATALOG: (catalogName: [myhive], properties: [{hive-conf-dir=/home/cutiechi/applications/hive/current/conf, default-database=mydatabase, type=hive}])
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.createCatalog(TableEnvironmentImpl.java:1301)
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1122)
        at org.apache.flink.table.client.gateway.local.LocalExecutor.lambda$executeOperation$3(LocalExecutor.java:209)
        at org.apache.flink.table.client.gateway.context.ExecutionContext.wrapClassLoader(ExecutionContext.java:88)
        at org.apache.flink.table.client.gateway.local.LocalExecutor.executeOperation(LocalExecutor.java:209)
        ... 8 more
Caused by: org.apache.flink.table.catalog.exceptions.CatalogException: Failed to create Hive Metastore client
        at org.apache.flink.table.catalog.hive.client.HiveShimV310.getHiveMetastoreClient(HiveShimV310.java:114)
        at org.apache.flink.table.catalog.hive.client.HiveMetastoreClientWrapper.createMetastoreClient(HiveMetastoreClientWrapper.java:277)
        at org.apache.flink.table.catalog.hive.client.HiveMetastoreClientWrapper.<init>(HiveMetastoreClientWrapper.java:78)
        at org.apache.flink.table.catalog.hive.client.HiveMetastoreClientWrapper.<init>(HiveMetastoreClientWrapper.java:68)
        at org.apache.flink.table.catalog.hive.client.HiveMetastoreClientFactory.create(HiveMetastoreClientFactory.java:32)
        at org.apache.flink.table.catalog.hive.HiveCatalog.open(HiveCatalog.java:296)
        at org.apache.flink.table.catalog.CatalogManager.registerCatalog(CatalogManager.java:195)
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.createCatalog(TableEnvironmentImpl.java:1297)
        ... 12 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.table.catalog.hive.client.HiveShimV310.getHiveMetastoreClient(HiveShimV310.java:112)
        ... 19 more
Caused by: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.metastore.HiveMetaStoreClient
        at org.apache.hadoop.hive.metastore.utils.JavaUtils.newInstance(JavaUtils.java:86)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:95)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:148)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:104)
        ... 24 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.hive.metastore.utils.JavaUtils.newInstance(JavaUtils.java:84)
        ... 27 more
Caused by: java.lang.NoSuchMethodError: com.facebook.fb303.FacebookService$Client.<init>(Lorg/apache/thrift/protocol/TProtocol;Lorg/apache/thrift/protocol/TProtocol;)V
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.<init>(ThriftHiveMetastore.java:892)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:513)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:224)
        ... 32 more (state=,code=0)
0: jdbc:hive2://192.168.9.70:10009>
```
### Affects Version(s)

master

### Kyuubi Engine Log Output

```logtalk
2022-03-16 18:31:22,287 INFO  org.apache.kyuubi.engine.flink.operation.ExecuteStatement    [] - Processing admin's query[7dd1721a-fa70-4829-b26d-18b19e4314e7]: RUNNING_STATE -> ERROR_STATE, statement: CREATE CATALOG myhive WITH ('type' = 'hive', 'default-database' = 'mydatabase', 'hive-conf-dir' = '/home/cutiechi/applications/hive/current/conf'), time taken: 0.046 seconds
2022-03-16 18:31:22,287 ERROR org.apache.kyuubi.engine.flink.FlinkTBinaryFrontendService   [] - Error fetching results: 
org.apache.kyuubi.KyuubiSQLException: OperationHandle [type=EXECUTE_STATEMENT, identifier: 7dd1721a-fa70-4829-b26d-18b19e4314e7] failed to generate operation log
        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69) ~[kyuubi-flink-sql-engine_2.12-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at org.apache.kyuubi.operation.OperationManager.$anonfun$getOperationLogRowSet$2(OperationManager.scala:125) ~[kyuubi-flink-sql-engine_2.12-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at scala.Option.getOrElse(Option.scala:121) ~[flink-dist_2.12-1.14.3.jar:1.14.3]
        at org.apache.kyuubi.operation.OperationManager.getOperationLogRowSet(OperationManager.scala:125) ~[kyuubi-flink-sql-engine_2.12-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at org.apache.kyuubi.session.AbstractSession.fetchResults(AbstractSession.scala:196) ~[kyuubi-flink-sql-engine_2.12-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at org.apache.kyuubi.service.AbstractBackendService.fetchResults(AbstractBackendService.scala:169) ~[kyuubi-flink-sql-engine_2.12-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at org.apache.kyuubi.service.TFrontendService.FetchResults(TFrontendService.scala:457) [kyuubi-flink-sql-engine_2.12-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at org.apache.kyuubi.shade.org.apache.hive.service.rpc.thrift.TCLIService$Processor$FetchResults.getResult(TCLIService.java:1837) [kyuubi-flink-sql-engine_2.12-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at org.apache.kyuubi.shade.org.apache.hive.service.rpc.thrift.TCLIService$Processor$FetchResults.getResult(TCLIService.java:1822) [kyuubi-flink-sql-engine_2.12-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at org.apache.kyuubi.shade.org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) [kyuubi-flink-sql-engine_2.12-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at org.apache.kyuubi.shade.org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) [kyuubi-flink-sql-engine_2.12-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at org.apache.kyuubi.service.authentication.TSetIpAddressProcessor.process(TSetIpAddressProcessor.scala:36) [kyuubi-flink-sql-engine_2.12-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at org.apache.kyuubi.shade.org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) [kyuubi-flink-sql-engine_2.12-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by cutiechi** [comment]
![image](https://user-images.githubusercontent.com/27606234/158572240-41ae8586-a0fb-4cb7-b5e0-8765651eb782.png)
libfb303 already in classpath

**Comment by cutiechi** [comment]
$FLINK_HOME/lib
<img width="609" alt="image" src="https://user-images.githubusercontent.com/27606234/158572663-6bcd68de-fba1-4d64-9081-b595ca1d477b.png">

**Comment by cutiechi** [comment]
@pan3793 i rebuild use latest commit was fine, but the exception log was messed up

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/27606234/158728503-10dd89e7-fd86-4a4e-bf37-a589ea8d19f5.png">

**Comment by pan3793** [comment]
Thanks for pointing this issue, seems we don't handle `newline` properly, we can improve it later cc @deadwind4.
I'm going to close this issue since it already have been addressed.
