### ISSUE TITLE
[Bug] Failed to delete session operation log directory

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#2227]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Meet error log when closing session.

### Affects Version(s)

1.6.0

### Kyuubi Server Log Output

```logtalk
00:56:09.042 ERROR org.apache.kyuubi.session.KyuubiSessionManager: Failed to delete session operation log directory /kyuubistaging_nfs/operation_logs/kyuubistaging-0.kyuubistaginghl.kyuubi-prod.svc.116.tess.io/f8a3163b-00cd-41b7-806e-a25c0934ff90
java.nio.file.DirectoryNotEmptyException: /kyuubistaging_nfs/operation_logs/kyuubistaging-0.kyuubistaginghl.kyuubi-prod.svc.116.tess.io/f8a3163b-00cd-41b7-806e-a25c0934ff90
      at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:242) ~[?:1.8.0_202]
      at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108) ~[?:1.8.0_202]
      at java.nio.file.Files.deleteIfExists(Files.java:1165) ~[?:1.8.0_202]
      at org.apache.kyuubi.session.SessionManager.$anonfun$deleteOperationLogSessionDir$1(SessionManager.scala:101) ~[kyuubi-common_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
      at scala.Option.foreach(Option.scala:407) ~[scala-library-2.12.15.jar:?]
      at org.apache.kyuubi.session.SessionManager.deleteOperationLogSessionDir(SessionManager.scala:98) ~[kyuubi-common_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
      at org.apache.kyuubi.session.SessionManager.closeSession(SessionManager.scala:92) ~[kyuubi-common_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
      at org.apache.kyuubi.service.AbstractBackendService.closeSession(AbstractBackendService.scala:49) ~[kyuubi-common_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
      at org.apache.kyuubi.server.KyuubiServer$$anon$1.org$apache$kyuubi$server$BackendServiceMetric$$super$closeSession(KyuubiServer.scala:144) ~[kyuubi-server_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
      at org.apache.kyuubi.server.BackendServiceMetric.$anonfun$closeSession$1(BackendServiceMetric.scala:43) ~[kyuubi-server_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
      at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23) ~[scala-library-2.12.15.jar:?]
      at org.apache.kyuubi.metrics.MetricsSystem$.timerTracing(MetricsSystem.scala:111) ~[kyuubi-metrics_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
      at org.apache.kyuubi.server.BackendServiceMetric.closeSession(BackendServiceMetric.scala:43) ~[kyuubi-server_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
      at org.apache.kyuubi.server.BackendServiceMetric.closeSession$(BackendServiceMetric.scala:41) ~[kyuubi-server_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
      at org.apache.kyuubi.server.KyuubiServer$$anon$1.closeSession(KyuubiServer.scala:144) ~[kyuubi-server_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
      at org.apache.kyuubi.service.TFrontendService.CloseSession(TFrontendService.scala:217) ~[kyuubi-common_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
      at org.apache.hive.service.rpc.thrift.TCLIService$Processor$CloseSession.getResult(TCLIService.java:1517) ~[hive-service-rpc-2.3.8.spark3.jar:2.3.8.spark3]
      at org.apache.hive.service.rpc.thrift.TCLIService$Processor$CloseSession.getResult(TCLIService.java:1502) ~[hive-service-rpc-2.3.8.spark3.jar:2.3.8.spark3]
      at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) ~[libthrift-0.9.3.jar:0.9.3]
      at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) ~[libthrift-0.9.3.jar:0.9.3]
      at org.apache.kyuubi.service.authentication.HadoopThriftAuthBridgeServer$TUGIAssumingProcessor.process(HadoopThriftAuthBridgeServer.scala:163) ~[kyuubi-common_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
      at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) ~[libthrift-0.9.3.jar:0.9.3]
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_202]
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_202]
      at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_202]
00:56:09.049 INFO org.apache.kyuubi.session.KyuubiSessionManager: SessionHandle [f8a3163b-00cd-41b7-806e-a25c0934ff90] is closed, current opening sessions 0
```
```


### Kyuubi Engine Log Output

_No response_

### Kyuubi Server Configurations

_No response_

### Kyuubi Engine Configurations

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
Related to https://github.com/apache/incubator-kyuubi/pull/2208#discussion_r835444874
