### ISSUE TITLE
[Bug] java.lang.NoClassDefFoundError: com/google/common/util/concurrent/SettableFuture

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#2228]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Meet class not found issue when getting hadoop fs delegation token.

### Affects Version(s)

1.6.0

### Kyuubi Server Log Output

```logtalk
01:00:05.324 INFO org.apache.hadoop.io.retry.RetryInvocationHandler: java.io.IOException: com.google.protobuf.ServiceException: java.lang.NoClassDefFoundError: com/google/common/util/concurrent/SettableFuture, while invoking ClientNamenodeProtocolTranslatorPB.getDelegationToken over *********:8020 after 1 failover attempts. Trying to failover after sleeping for 644ms.
```
```


### Kyuubi Engine Log Output

_No response_

### Kyuubi Server Configurations

_No response_

### Kyuubi Engine Configurations

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by turboFei** [comment]
```
01:03:03.467 WARN org.apache.kyuubi.credentials.HadoopCredentialsManager: Failed to update tokens for b_stf, try again in 60000 ms
java.io.IOException: com.google.protobuf.ServiceException: java.lang.NoClassDefFoundError: com/google/common/util/concurrent/SettableFuture
	at org.apache.hadoop.ipc.ProtobufHelper.getRemoteException(ProtobufHelper.java:47) ~[hadoop-common-2.7.3.2.6.4.2.0.18.jar:?]
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getDelegationToken(ClientNamenodeProtocolTranslatorPB.java:1366) ~[hadoop-hdfs-2.7.3.2.6.4.2.0.18.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:291) ~[hadoop-common-2.7.3.2.6.4.2.0.18.jar:?]
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:203) ~[hadoop-common-2.7.3.2.6.4.2.0.18.jar:?]
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:185) ~[hadoop-common-2.7.3.2.6.4.2.0.18.jar:?]
	at com.sun.proxy.$Proxy28.getDelegationToken(Unknown Source) ~[?:?]
	at org.apache.hadoop.hdfs.DFSClient.getDelegationToken(DFSClient.java:1053) ~[hadoop-hdfs-2.7.3.2.6.4.2.0.18.jar:?]
	at org.apache.hadoop.hdfs.DistributedFileSystem.getDelegationToken(DistributedFileSystem.java:1718) ~[hadoop-hdfs-2.7.3.2.6.4.2.0.18.jar:?]
	at org.apache.hadoop.fs.FileSystem.collectDelegationTokens(FileSystem.java:549) ~[hadoop-common-2.7.3.2.6.4.2.0.18.jar:?]
	at org.apache.hadoop.fs.FileSystem.collectDelegationTokens(FileSystem.java:560) ~[hadoop-common-2.7.3.2.6.4.2.0.18.jar:?]
	at org.apache.hadoop.fs.FileSystem.addDelegationTokens(FileSystem.java:527) ~[hadoop-common-2.7.3.2.6.4.2.0.18.jar:?]
	at org.apache.kyuubi.credentials.HadoopFsDelegationTokenProvider.$anonfun$obtainDelegationTokens$3(HadoopFsDelegationTokenProvider.scala:73) ~[kyuubi-server_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
	at scala.collection.immutable.Set$Set4.foreach(Set.scala:289) ~[scala-library-2.12.15.jar:?]
	at org.apache.kyuubi.credentials.HadoopFsDelegationTokenProvider.$anonfun$obtainDelegationTokens$1(HadoopFsDelegationTokenProvider.scala:71) ~[kyuubi-server_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23) ~[scala-library-2.12.15.jar:?]
	at org.apache.kyuubi.credentials.HadoopFsDelegationTokenProvider$$anon$1.run(HadoopFsDelegationTokenProvider.scala:109) ~[kyuubi-server_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_202]
	at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_202]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1888) ~[hadoop-common-2.7.3.2.6.4.2.0.18.jar:?]
	at org.apache.kyuubi.credentials.HadoopFsDelegationTokenProvider$.doAsProxyUser(HadoopFsDelegationTokenProvider.scala:108) ~[kyuubi-server_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
	at org.apache.kyuubi.credentials.HadoopFsDelegationTokenProvider.obtainDelegationTokens(HadoopFsDelegationTokenProvider.scala:65) ~[kyuubi-server_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
	at org.apache.kyuubi.credentials.HadoopCredentialsManager.$anonfun$updateCredentials$2(HadoopCredentialsManager.scala:261) ~[kyuubi-server_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
	at org.apache.kyuubi.credentials.HadoopCredentialsManager.$anonfun$updateCredentials$2$adapted(HadoopCredentialsManager.scala:260) ~[kyuubi-server_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286) ~[scala-library-2.12.15.jar:?]
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:273) ~[scala-library-2.12.15.jar:?]
	at scala.collection.TraversableLike.map(TraversableLike.scala:286) ~[scala-library-2.12.15.jar:?]
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279) ~[scala-library-2.12.15.jar:?]
	at scala.collection.AbstractTraversable.map(Traversable.scala:108) ~[scala-library-2.12.15.jar:?]
	at org.apache.kyuubi.credentials.HadoopCredentialsManager.org$apache$kyuubi$credentials$HadoopCredentialsManager$$updateCredentials(HadoopCredentialsManager.scala:260) ~[kyuubi-server_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
	at org.apache.kyuubi.credentials.HadoopCredentialsManager$$anon$1.run(HadoopCredentialsManager.scala:275) ~[kyuubi-server_2.12-1.6.0-ebay-SNAPSHOT.jar:1.6.0-ebay-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_202]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_202]
Caused by: com.google.protobuf.ServiceException: java.lang.NoClassDefFoundError: com/google/common/util/concurrent/SettableFuture
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:274) ~[hadoop-common-2.7.3.2.6.4.2.0.18.jar:?]
	at com.sun.proxy.$Proxy27.getDelegationToken(Unknown Source) ~[?:?]
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getDelegationToken(ClientNamenodeProtocolTranslatorPB.java:1362) ~[hadoop-hdfs-2.7.3.2.6.4.2.0.18.jar:?]
	... 39 more
Caused by: java.lang.NoClassDefFoundError: com/google/common/util/concurrent/SettableFuture
	at com.google.common.cache.LocalCache$LoadingValueReference.<init>(LocalCache.java:3472) ~[guava-30.1-jre.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.<init>(LocalCache.java:3476) ~[guava-30.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2134) ~[guava-30.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[guava-30.1-jre.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951) ~[guava-30.1-jre.jar:?]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4848) ~[guava-30.1-jre.jar:?]
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1896) ~[hadoop-common-2.7.3.2.6.4.2.0.18.jar:?]
	at org.apache.hadoop.ipc.Client.call(Client.java:1666) ~[hadoop-common-2.7.3.2.6.4.2.0.18.jar:?]
	at org.apache.hadoop.ipc.Client.call(Client.java:1597) ~[hadoop-common-2.7.3.2.6.4.2.0.18.jar:?]
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:260) ~[hadoop-common-2.7.3.2.6.4.2.0.18.jar:?]
	at com.sun.proxy.$Proxy27.getDelegationToken(Unknown Source) ~[?:?]
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getDelegationToken(ClientNamenodeProtocolTranslatorPB.java:1362) ~[hadoop-hdfs-2.7.3.2.6.4.2.0.18.jar:?]
	... 39 more
```

**Comment by turboFei** [comment]
The guava version for kyuubi is 30.0
and that of hadoop lib is guava-11.0.2.jar.

**Comment by turboFei** [comment]
I wonder whether it is related with #1716 
Let me revert it and have a try.
