### ISSUE TITLE
[Bug] cannot execute statement locally after code change in PR #2214

### ISSUE THREAD

**Issue by lightning-L** [apache/incubator-kyuubi#2328]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

```
 }.orElse {
      // 3. get the main resource from dev environment
      val cwd = getClass.getProtectionDomain.getCodeSource.getLocation.getPath
        .split("kyuubi-server")
      assert(cwd.length > 1)
      Option(Paths.get(cwd.head, "externals", module, "target", jarName))
        .map(_.toAbsolutePath.toFile.getCanonicalPath)
    }
```
the `cwd` is not getting the correct path for local build.

It should be `<my_local_path>/incubator-kyuubi/`, but it is getting: `<my_local_path>/incubator-kyuubi/kyuubi-assembly/target/scala-2.12/jars/`.

How to reproduce:
```
build/mvn clean package -Pmirror-cdn -DskipTests

bin/kyuubi start

$SPARK_HOME/bin/beeline -u "jdbc:hive2://xxxx:10009"  (or using bin/beeline)

then execute statement, for example, select timestamp '2018-11-17';
```

When executing statement, error is thrown:
```
22/04/11 18:29:55 WARN DependencyUtils: Local jar /Users/tiliao/Documents/Code/incubator-kyuubi/kyuubi-assembly/target/scala-2.12/jars/externals/kyuubi-spark-sql-engine/target/kyuubi-spark-sql-engine_2.12-1.6.0-SNAPSHOT.jar does not exist, skipping.
```

### Affects Version(s)

1.6.0

### Kyuubi Server Log Output

```logtalk
18:29:52.248 INFO org.apache.kyuubi.engine.EngineRef: Launching engine:
/Users/tiliao/Documents/Software/spark-3.2.1-bin-hadoop2.7/bin/spark-submit \
        --class org.apache.kyuubi.engine.spark.SparkSQLEngine \
        --conf spark.kyuubi.session.engine.idle.timeout=PT10M \
        --conf spark.hive.server2.thrift.resultset.default.fetch.size=1000 \
        --conf spark.kyuubi.ha.zookeeper.quorum=192.168.31.130:2181 \
        --conf spark.kyuubi.client.ip=192.168.31.130 \
        --conf spark.kyuubi.engine.submit.time=1649672992214 \
        --conf spark.app.name=kyuubi_USER_SPARK_SQL_anonymous_default_98374ac9-17d3-4bc5-a77a-56d4c223df3f \
        --conf spark.kyuubi.ha.engine.ref.id=98374ac9-17d3-4bc5-a77a-56d4c223df3f \
        --conf spark.kyuubi.ha.zookeeper.auth.type=NONE \
        --conf spark.kyuubi.session.engine.spark.max.lifetime=PT2M \
        --conf spark.yarn.tags=KYUUBI \
        --conf spark.kyuubi.ha.zookeeper.namespace=/kyuubi_1.6.0-SNAPSHOT_USER_SPARK_SQL/anonymous/default \
        --proxy-user anonymous /Users/tiliao/Documents/Code/incubator-kyuubi/kyuubi-assembly/target/scala-2.12/jars/externals/kyuubi-spark-sql-engine/target/kyuubi-spark-sql-engine_2.12-1.6.0-SNAPSHOT.jar

...

18:29:59.216 ERROR org.apache.kyuubi.server.KyuubiTBinaryFrontendService: Error executing statement:
java.util.concurrent.ExecutionException: org.apache.kyuubi.KyuubiSQLException: org.apache.kyuubi.KyuubiSQLException: Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
 See more: /Users/tiliao/Documents/Code/incubator-kyuubi/work/anonymous/kyuubi-spark-sql-engine.log.3
        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
        at org.apache.kyuubi.engine.ProcBuilder.$anonfun$start$1(ProcBuilder.scala:165)
        at java.lang.Thread.run(Thread.java:748)
.
FYI: The last 10 line(s) of log are:
Caused by: org.apache.spark.SparkUserAppException: User application exited with 101
at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
at org.apache.spark.deploy.SparkSubmit$$anon$1.run(SparkSubmit.scala:165)
at org.apache.spark.deploy.SparkSubmit$$anon$1.run(SparkSubmit.scala:163)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
... 6 more
```

### Kyuubi Engine Log Output

```logtalk
22/04/11 18:29:55 WARN DependencyUtils: Local jar /Users/tiliao/Documents/Code/incubator-kyuubi/kyuubi-assembly/target/scala-2.12/jars/externals/kyuubi-spark-sql-engine/target/kyuubi-spark-sql-engine_2.12-1.6.0-SNAPSHOT.jar does not exist, skipping.
Error: Failed to load class org.apache.kyuubi.engine.spark.SparkSQLEngine.
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1761)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:163)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.spark.SparkUserAppException: User application exited with 101
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
        at org.apache.spark.deploy.SparkSubmit$$anon$1.run(SparkSubmit.scala:165)
        at org.apache.spark.deploy.SparkSubmit$$anon$1.run(SparkSubmit.scala:163)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
        ... 6 more
```

### Kyuubi Server Configurations

```yaml
default
```

### Kyuubi Engine Configurations

```yaml
default
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wForget** [comment]
Do you run `bin/kyuubi start` in the kyuubi source dir?

**Comment by lightning-L** [comment]
yes, I am running in the source dir. which is `/Users/tiliao/Documents/Code/incubator-kyuubi` in my local.

**Comment by wForget** [comment]
> yes, I am running in the source dir. which is `/Users/tiliao/Documents/Code/incubator-kyuubi` in my local.

This doesn't look like a good way, you can start kyuubi in kyuubi dist dir.

**Comment by pan3793** [comment]
> I am running in the source dir. 

We should support such dev mode

**Comment by ulysses-you** [comment]
@wForget looks good if works

**Comment by wForget** [comment]
> @wForget looks good if works. Can you send a pr ?

sure, I will send a pr later.
