### ISSUE TITLE
[Bug] beeline Connection failed

### ISSUE THREAD

**Issue by Narcasserun** [apache/incubator-kyuubi#2362]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

![image](https://user-images.githubusercontent.com/39329477/163328152-6117dc29-9fb2-4354-afa7-a3aaae9a4c68.png)

### Affects Version(s)

1.5.0

### Kyuubi Engine Log Output

```logtalk
14:33:25.386 INFO org.apache.kyuubi.engine.ProcBuilder: Logging to /home/maolin/apache-kyuubi-1.5.0-incubating-bin/work/root/kyuubi-spark-sql-engine.log.26
14:33:25.426 ERROR org.apache.kyuubi.server.KyuubiTBinaryFrontendService: Error getting type info:
org.apache.kyuubi.KyuubiSQLException: Unrecognized GetInfoType value: CLI_ODBC_KEYWORDS
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69) ~[kyuubi-common_2.12-1.5.0-incubating.jar:1.5.0-incubating]
	at org.apache.kyuubi.session.AbstractSession.$anonfun$getInfo$1(AbstractSession.scala:111) ~[kyuubi-common_2.12-1.5.0-incubating.jar:1.5.0-incubating]
	at org.apache.kyuubi.session.AbstractSession.withAcquireRelease(AbstractSession.scala:75) ~[kyuubi-common_2.12-1.5.0-incubating.jar:1.5.0-incubating]
	at org.apache.kyuubi.session.AbstractSession.getInfo(AbstractSession.scala:104) ~[kyuubi-common_2.12-1.5.0-incubating.jar:1.5.0-incubating]
	at org.apache.kyuubi.service.AbstractBackendService.getInfo(AbstractBackendService.scala:53) ~[kyuubi-common_2.12-1.5.0-incubating.jar:1.5.0-incubating]
	at org.apache.kyuubi.server.KyuubiServer$$anon$1.org$apache$kyuubi$server$BackendServiceMetric$$super$getInfo(KyuubiServer.scala:142) ~[kyuubi-server_2.12-1.5.0-incubating.jar:1.5.0-incubating]
	at org.apache.kyuubi.server.BackendServiceMetric.$anonfun$getInfo$1(BackendServiceMetric.scala:51) ~[kyuubi-server_2.12-1.5.0-incubating.jar:1.5.0-incubating]
	at org.apache.kyuubi.metrics.MetricsSystem$.timerTracing(MetricsSystem.scala:111) ~[kyuubi-metrics_2.12-1.5.0-incubating.jar:1.5.0-incubating]
	at org.apache.kyuubi.server.BackendServiceMetric.getInfo(BackendServiceMetric.scala:51) ~[kyuubi-server_2.12-1.5.0-incubating.jar:1.5.0-incubating]
	at org.apache.kyuubi.server.BackendServiceMetric.getInfo$(BackendServiceMetric.scala:47) ~[kyuubi-server_2.12-1.5.0-incubating.jar:1.5.0-incubating]
	at org.apache.kyuubi.server.KyuubiServer$$anon$1.getInfo(KyuubiServer.scala:142) ~[kyuubi-server_2.12-1.5.0-incubating.jar:1.5.0-incubating]
	at org.apache.kyuubi.service.TFrontendService.GetInfo(TFrontendService.scala:206) ~[kyuubi-common_2.12-1.5.0-incubating.jar:1.5.0-incubating]
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetInfo.getResult(TCLIService.java:1537) ~[hive-service-rpc-3.1.2.jar:3.1.2]
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetInfo.getResult(TCLIService.java:1522) ~[hive-service-rpc-3.1.2.jar:3.1.2]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.kyuubi.service.authentication.TSetIpAddressProcessor.process(TSetIpAddressProcessor.scala:36) ~[kyuubi-common_2.12-1.5.0-incubating.jar:1.5.0-incubating]
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) ~[libthrift-0.9.3.jar:0.9.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_321]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_321]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_321]
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by turboFei** [comment]
could you try to use Kyuubi Beeline？
