### ISSUE TITLE
[Bug] Travis CI Test Failed - hive process builder *** FAILED ***

### ISSUE THREAD

**Issue by Nick-0723** [apache/incubator-kyuubi#2370]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Travis CI test failed, seems travis config does not have java envrionment

```
- hive process builder *** FAILED ***
  org.apache.kyuubi.KyuubiSQLException: JAVA_HOME is not set! For more information on installing and configuring JAVA_HOME, please visit https://kyuubi.apache.org/docs/latest/deployment/settings.html#environments
  at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
  at org.apache.kyuubi.engine.ProcBuilder.validateEnv(ProcBuilder.scala:326)
  at org.apache.kyuubi.engine.ProcBuilder.validateEnv$(ProcBuilder.scala:325)
  at org.apache.kyuubi.engine.hive.HiveProcessBuilder.validateEnv(HiveProcessBuilder.scala:33)
  at org.apache.kyuubi.engine.ProcBuilder.executable(ProcBuilder.scala:52)
  at org.apache.kyuubi.engine.ProcBuilder.executable$(ProcBuilder.scala:49)
  at org.apache.kyuubi.engine.hive.HiveProcessBuilder.executable(HiveProcessBuilder.scala:33)
  at org.apache.kyuubi.engine.hive.HiveProcessBuilder.commands(HiveProcessBuilder.scala:47)
  at org.apache.kyuubi.engine.hive.HiveProcessBuilder.toString(HiveProcessBuilder.scala:89)
  at org.apache.kyuubi.engine.hive.HiveProcessBuilderSuite.$anonfun$new$1(HiveProcessBuilderSuite.scala:29)
```

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Nick-0723** [comment]
fixed by #2385
