### ISSUE TITLE
[Bug] Hive engine throw NPE in get operation status

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2490]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

```
2022-04-27T18:57:51,619 ERROR [HiveTBinaryFrontendHandler-Pool: Thread-34] org.apache.kyuubi.engine.hive.HiveTBinaryFrontendService - Error getting operation status:
java.lang.NullPointerException: null
	at org.apache.kyuubi.service.AbstractBackendService.getOperationStatus(AbstractBackendService.scala:163) ~[kyuubi-hive-sql-engine_2.12-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
	at org.apache.kyuubi.service.TFrontendService.GetOperationStatus(TFrontendService.scala:419) [kyuubi-hive-sql-engine_2.12-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetOperationStatus.getResult(TCLIService.java:1757) [hive-service-rpc-3.1.3.jar:3.1.3]
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetOperationStatus.getResult(TCLIService.java:1742) [hive-service-rpc-3.1.3.jar:3.1.3]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) [libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) [libthrift-0.9.3.jar:0.9.3]
	at org.apache.kyuubi.service.authentication.TSetIpAddressProcessor.process(TSetIpAddressProcessor.scala:36) [kyuubi-hive-sql-engine_2.12-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) [libthrift-0.9.3.jar:0.9.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

for hive operation, the getBackgroundHandle maybe null

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wForget** [comment]
@yaooqinn Could you please assign this to me?

**Comment by yaooqinn** [comment]
thanks @wForget
