### ISSUE TITLE
[Bug] Missing classes for beeline after upgrading Hive 3.1

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#2614]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

```
➜  apache-kyuubi git:(master) beeline
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/io/output/StringBuilderWriter
	at org.apache.hive.beeline.BeeLine.<init>(BeeLine.java:177)
	at org.apache.hive.beeline.KyuubiBeeLine.<init>(KyuubiBeeLine.java:44)
	at org.apache.hive.beeline.KyuubiBeeLine.<init>(KyuubiBeeLine.java:40)
	at org.apache.hive.beeline.KyuubiBeeLine.mainWithInputRedirection(KyuubiBeeLine.java:80)
	at org.apache.hive.beeline.KyuubiBeeLine.main(KyuubiBeeLine.java:67)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.output.StringBuilderWriter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 5 more
```

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
cc @gabrywu

**Comment by gabrywu** [comment]
> cc @gabrywu

I will try to fix it, and don't upgrade beeline yet
