### ISSUE TITLE
[Improvement] Spark engine supports local mode in kerberos environment

### ISSUE THREAD

**Issue by cxzl25** [apache/incubator-kyuubi#2831]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Now in the kerberos environment, the spark engine cannot access the Hive meta store using `spark-submit --master=local --proxy-user xxx`.

```
beeline -u "jdbc:hive2://XXXX/default;principal=XXXX/_HOST@XXXX;#kyuubi.engine.share.level=CONNECTION;spark.master=local;spark.submit.deployMode=client;"
```

```
javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]

        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1743)
        at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport.open(TUGIAssumingTransport.java:49)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:483)
```

### How should we improve?

After initializing the spark session, obtain a hive delegation token.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by cxzl25** [comment]
Closed in favour of https://github.com/apache/incubator-kyuubi/issues/2708
