### ISSUE TITLE
[Bug] Error when connecting to kyuubi

### ISSUE THREAD

**Issue by Narcasserun** [apache/incubator-kyuubi#2874]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

ERROR spark.SparkSQLEngine: Failed to instantiate SparkSession: org.apache.hadoop.hive.ql.metadata.HiveException: org.apache.thrift.TApplicationException: Invalid method name: 'get_database_req'
org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: org.apache.thrift.TApplicationException: Invalid method name: 'get_database_req'

spark:3.2.1
hive:3.1
spark.sql.hive.metastore.jars. hive-3.1

### Affects Version(s)

1.5.1

### Kyuubi Server Log Output

```logtalk
10:33:22.236 INFO org.apache.zookeeper.ZooKeeper: Session: 0x37c7fff1098639d closed
10:33:22.243 INFO org.apache.zookeeper.ClientCnxn: EventThread shut down for session: 0x37c7fff1098639d
10:33:22.255 INFO org.apache.kyuubi.operation.LaunchEngine: Processing root's query[971b86eb-9fe1-4fc9-8c13-39b9bd64e06b]: RUNNING_STATE -> ERROR_STATE, statement: LAUNCH_ENGINE, time taken: 180.102 seconds
10:33:22.261 ERROR org.apache.kyuubi.server.KyuubiTBinaryFrontendService: Error executing statement: 
java.util.concurrent.ExecutionException: org.apache.kyuubi.KyuubiSQLException: Timeout(180000 ms) to launched SPARK_SQL engine with /home/nagios/maolin/spark-3.2.1-bin-hadoop2.7/bin/spark-submit \
	--class org.apache.kyuubi.engine.spark.SparkSQLEngine \
	--conf spark.kyuubi.session.engine.idle.timeout=PT30M \
	--conf spark.kyuubi.ha.zookeeper.quorum=192.168.134.40 \
	--conf spark.kyuubi.client.ip=192.168.134.61 \
	--conf spark.kyuubi.session.engine.request.timeout=PT10M \
	--conf spark.yarn.queue=llyt \
	--conf spark.kyuubi.engine.submit.time=1655173822199 \
	--conf spark.kyuubi.ha.zookeeper.client.port=2181 \
	--conf spark.app.name=kyuubi_CONNECTION_SPARK_SQL_root_c86ea32c-e7c9-4c10-ab82-a332f16443c5 \
	--conf spark.driver.memory=1G \
	--conf spark.executor.instances=1 \
	--conf spark.job.priority=10 \
	--conf spark.kyuubi.ha.zookeeper.session.timeout=600000 \
	--conf spark.kyuubi.ha.engine.ref.id=c86ea32c-e7c9-4c10-ab82-a332f16443c5 \
	--conf spark.driver.cores=1 \
	--conf spark.executor.cores=1 \
	--conf spark.submit.deployMode=client \
	--conf spark.master=yarn \
	--conf spark.yarn.tags=KYUUBI \
	--conf spark.executor.instances=1 \
	--conf spark.kyuubi.engine.share.level=CONNECTION \
	--conf spark.kyuubi.ha.zookeeper.namespace=/kyuubi_ns_1.5.1-SNAPSHOT_CONNECTION_SPARK_SQL/root/c86ea32c-e7c9-4c10-ab82-a332f16443c5 \
	--conf spark.executor.memory=1G \
	--conf spark.executor.cores=1 \
	--conf spark.kyuubi.ha.enabled=true \
	--proxy-user root /home/nagios/maolin/apache-kyuubi-1.5.1-SNAPSHOT-bin/externals/engines/spark/kyuubi-spark-sql-engine_2.12-1.5.1-SNAPSHOT.jar. 
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_45]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_45]
	at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$waitForEngineLaunched$1(KyuubiSessionImpl.scala:131) ~[kyuubi-server_2.12-1.5.1-SNAPSHOT.jar:1.5.1-SNAPSHOT]
	at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$waitForEngineLaunched$1$adapted(KyuubiSessionImpl.scala:127) ~[kyuubi-server_2.12-1.5.1-SNAPSHOT.jar:1.5.1-SNAPSHOT]
	at org.apache.kyuubi.session.KyuubiSessionImpl$$Lambda$327/210839684.apply(Unknown Source) ~[?:?]
	at scala.Option.foreach(Option.scala:407) ~[scala-library-2.12.15.jar:?]
	at org.apache.kyuubi.session.KyuubiSessionImpl.waitForEngineLaunched(KyuubiSessionImpl.scala:127) ~[kyuubi-server_2.12-1.5.1-SNAPSHOT.jar:1.5.1-SNAPSHOT]
	at org.apache.kyuubi.session.KyuubiSessionImpl.runOperation(KyuubiSessionImpl.scala:117) ~[kyuubi-server_2.12-1.5.1-SNAPSHOT.jar:1.5.1-SNAPSHOT]
	at org.apache.kyuubi.session.AbstractSession.$anonfun$executeStatement$1(AbstractSession.scala:122) ~[kyuubi-common_2.12-1.5.1-SNAPSHOT.jar:1.5.1-SNAPSHOT]
	at org.apache.kyuubi.session.AbstractSession$$Lambda$322/252860322.apply(Unknown Source) ~[?:?]
	at org.apache.kyuubi.session.AbstractSession.withAcquireRelease(AbstractSession.scala:75) ~[kyuubi-common_2.12-1.5.1-SNAPSHOT.jar:1.5.1-SNAPSHOT]
	at org.apache.kyuubi.session.AbstractSession.executeStatement(AbstractSession.scala:119) ~[kyuubi-common_2.12-1.5.1-SNAPSHOT.jar:1.5.1-SNAPSHOT]
	at org.apache.kyuubi.service.AbstractBackendService.executeStatement(AbstractBackendService.scala:66) ~[kyuubi-common_2.12-1.5.1-SNAPSHOT.jar:1.5.1-SNAPSHOT]
	at org.apache.kyuubi.server.KyuubiServer$$anon$1.org$apache$kyuubi$server$BackendServiceMetric$$super$executeStatement(KyuubiServer.scala:142) ~[kyuubi-server_2.12-1.5.1-SNAPSHOT.jar:1.5.1-SNAPSHOT]
	at org.apache.kyuubi.server.BackendServiceMetric.$anonfun$executeStatement$1(BackendServiceMetric.scala:62) ~[kyuubi-server_2.12-1.5.1-SNAPSHOT.jar:1.5.1-SNAPSHOT]
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: org.apache.thrift.TApplicationException: Invalid method name: 'get_database_req'
	at org.apache.hadoop.hive.ql.metadata.Hive.getDatabase(Hive.java:1992)
	at org.apache.hadoop.hive.ql.metadata.Hive.databaseExists(Hive.java:1977)
	at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$databaseExists$1(HiveClientImpl.scala:396)
	at org.apache.spark.sql.hive.client.HiveClientImpl$$Lambda$2017/1631805946.apply$mcZ$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$withHiveState$1(HiveClientImpl.scala:305)
	at org.apache.spark.sql.hive.client.HiveClientImpl$$Lambda$2018/1401589925.apply(Unknown Source)
	at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:236)
	at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:235)
	at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:285)
	at org.apache.spark.sql.hive.client.HiveClientImpl.databaseExists(HiveClientImpl.scala:396)
 See more: /home/nagios/maolin/apache-kyuubi-1.5.1-SNAPSHOT-bin/work/root/kyuubi-spark-sql-engine.log.0
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69) ~[kyuubi-common_2.12-1.5.1-SNAPSHOT.jar:1.5.1-SNAPSHOT]
	at org.apache.kyuubi.engine.ProcBuilder.$anonfun$start$1(ProcBuilder.scala:165) ~[kyuubi-server_2.12-1.5.1-SNAPSHOT.jar:1.5.1-SNAPSHOT]
	at org.apache.kyuubi.engine.ProcBuilder$$Lambda$335/858694918.run(Unknown Source) ~[?:?]
```

### Kyuubi Engine Log Output

```logtalk
at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: org.apache.thrift.TApplicationException: Invalid method name: 'get_database_req'
	at org.apache.hadoop.hive.ql.metadata.Hive.getDatabase(Hive.java:1992)
	at org.apache.hadoop.hive.ql.metadata.Hive.databaseExists(Hive.java:1977)
	at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$databaseExists$1(HiveClientImpl.scala:396)
	at org.apache.spark.sql.hive.client.HiveClientImpl$$Lambda$2017/1631805946.apply$mcZ$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$withHiveState$1(HiveClientImpl.scala:305)
	at org.apache.spark.sql.hive.client.HiveClientImpl$$Lambda$2018/1401589925.apply(Unknown Source)
	at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:236)
	at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:235)
	at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:285)
	at org.apache.spark.sql.hive.client.HiveClientImpl.databaseExists(HiveClientImpl.scala:396)
 See more: /home/nagios/maolin/apache-kyuubi-1.5.1-SNAPSHOT-bin/work/root/kyuubi-spark-sql-engine.log.0
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69) ~[kyuubi-common_2.12-1.5.1-SNAPSHOT.jar:1.5.1-SNAPSHOT]
	at org.apache.kyuubi.engine.ProcBuilder.$anonfun$start$1(ProcBuilder.scala:165) ~[kyuubi-server_2.12-1.5.1-SNAPSHOT.jar:1.5.1-SNAPSHOT]
	at org.apache.kyuubi.engine.ProcBuilder$$Lambda$335/858694918.run(Unknown Source) ~[?:?]
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Narcasserun** [comment]
@pan3793

**Comment by yaooqinn** [comment]
https://kyuubi.readthedocs.io/en/latest/monitor/trouble_shooting.html#org-apache-thrift-tapplicationexception-invalid-method-name-get-table-req
