### ISSUE TITLE
HUE Error operating EXECUTE_STATEMENT, broken pipe(Write failed) 

### ISSUE THREAD

**Issue by lixk666** [apache/incubator-kyuubi#2877]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When I use Hue to connect to Kyuubi of USER engine level in Hiveserver2 mode, the Engine of Kyuubi can be created and the application can be displayed on yarn 8088. However, when I kill the engine, or when I use Hue to connect to Kyuubi again due to a query error, I am informed of the following error
Error operating EXECUTE_STATEMENT: org.apache.thrift.transport.TTransportException: java.new.SocketException: Broken pipe(Write failed) at org.apache.thrift.transport.TIOStreamTransport.flush(TIOStreamTransport.java:161)

![image](https://user-images.githubusercontent.com/52159212/173504019-6f30b1be-a1fd-4bc2-a306-cdea060ee5e4.png)

### Affects Version(s)

1.5.1

### Kyuubi Server Log Output

```logtalk
13:49:57.369 INFO org.apache.kyuubi.operation.ExecuteStatement: Processing user01's query[2c237d75-f33e-476e-ae47-61bc0aa70030]: PENDING_STATE -> ERROR_STATE, statement: USE `default`, time taken: 1.655185797369E9 seconds
13:49:57.369 INFO org.apache.kyuubi.operation.ExecuteStatement: Processing user01's query[2c237d75-f33e-476e-ae47-61bc0aa70030]: ERROR_STATE -> CLOSED_STATE, statement: USE `default`
13:49:57.370 ERROR org.apache.kyuubi.server.KyuubiTBinaryFrontendService: Error executing statement:
org.apache.kyuubi.KyuubiSQLException: Error operating EXECUTE_STATEMENT: org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe (Write failed)
at org.apache.thrift.transport.TIOStreamTransport.flush(TIOStreamTransport.java:161)
at org.apache.thrift.transport.TSaslTransport.flush(TSaslTransport.java:501)
at org.apache.thrift.transport.TSaslClientTransport.flush(TSaslClientTransport.java:37)
at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:73)
at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
at org.apache.hive.service.rpc.thrift.TCLIService$Client.send_ExecuteStatement(TCLIService.java:239)
at org.apache.hive.service.rpc.thrift.TCLIService$Client.ExecuteStatement(TCLIService.java:231)
at org.apache.kyuubi.client.KyuubiSyncThriftClient.$anonfun$executeStatement$1(KyuubiSyncThriftClient.scala:107)
at org.apache.kyuubi.client.KyuubiSyncThriftClient.withLockAcquired(KyuubiSyncThriftClient.scala:54)
at org.apache.kyuubi.client.KyuubiSyncThriftClient.executeStatement(KyuubiSyncThriftClient.scala:107)
at org.apache.kyuubi.operation.ExecuteStatement.executeStatement(ExecuteStatement.scala:71)
at org.apache.kyuubi.operation.ExecuteStatement.runInternal(ExecuteStatement.scala:164)
at org.apache.kyuubi.operation.AbstractOperation.run(AbstractOperation.scala:133)
at org.apache.kyuubi.session.AbstractSession.runOperation(AbstractSession.scala:93)
at org.apache.kyuubi.session.KyuubiSessionImpl.runOperation(KyuubiSessionImpl.scala:120)
at org.apache.kyuubi.session.AbstractSession.$anonfun$executeStatement$1(AbstractSession.scala:122)
at org.apache.kyuubi.session.AbstractSession.withAcquireRelease(AbstractSession.scala:75)
at org.apache.kyuubi.session.AbstractSession.executeStatement(AbstractSession.scala:119)
at org.apache.kyuubi.service.AbstractBackendService.executeStatement(AbstractBackendService.scala:66)
at org.apache.kyuubi.server.KyuubiServer$$anon$1.org$apache$kyuubi$server$BackendServiceMetric$$super$executeStatement(KyuubiServer.scala:142)
at org.apache.kyuubi.server.BackendServiceMetric.$anonfun$executeStatement$1(BackendServiceMetric.scala:62)
at org.apache.kyuubi.metrics.MetricsSystem$.timerTracing(MetricsSystem.scala:111)
at org.apache.kyuubi.server.BackendServiceMetric.executeStatement(BackendServiceMetric.scala:62)
at org.apache.kyuubi.server.BackendServiceMetric.executeStatement$(BackendServiceMetric.scala:55)
```

### Kyuubi Engine Log Output

```logtalk
22/06/14 13:48:20 INFO yarn.Client: Application report for application_1648627124991_7880 (state: RUNNING)
22/06/14 13:48:21 INFO yarn.Client: Application report for application_1648627124991_7880 (state: RUNNING)
22/06/14 13:48:22 INFO yarn.Client: Application report for application_1648627124991_7880 (state: RUNNING)
22/06/14 13:48:23 INFO yarn.Client: Application report for application_1648627124991_7880 (state: RUNNING)
22/06/14 13:48:24 INFO yarn.Client: Application report for application_1648627124991_7880 (state: RUNNING)
22/06/14 13:48:25 INFO yarn.Client: Application report for application_1648627124991_7880 (state: RUNNING)
22/06/14 13:48:26 INFO yarn.Client: Application report for application_1648627124991_7880 (state: RUNNING)
22/06/14 13:48:27 INFO yarn.Client: Application report for application_1648627124991_7880 (state: RUNNING)
22/06/14 13:48:28 INFO yarn.Client: Application report for application_1648627124991_7880 (state: FINISHED)
22/06/14 13:48:28 INFO yarn.Client:
client token: Token { kind: YARN_CLIENT_TOKEN, service: }
diagnostics: N/A
ApplicationMaster host: IPXXXX.cn
ApplicationMaster RPC port: 35963
queue: root.FMSPool
start time: 1655185133541
final status: SUCCEEDED
tracking URL: http://ipXXXX:8088/proxy/application_1648627124991_7880/
user: os-donglei01
22/06/14 13:48:28 INFO util.ShutdownHookManager: Shutdown hook called
22/06/14 13:48:28 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-e37b0896-a58b-4b4f-82e8-0528095307fc
22/06/14 13:48:28 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-5ba1c3bb-5999-4f2f-8ec0-db4b07847df7
```

### Additional context

When I used the beeline command line on a Linux server to authenticate Kyuubi either using Kinit or LDAP, I was successful. In Hue, however, it always fails

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by lixk666** [comment]
@pan3793 Thanks for your answer,it does work.

**Comment by dachn** [comment]
i got same probles,did it soved?

**Comment by dachn** [comment]
> You are trying to connect a broken session, IIRC there is a button on the HUE top area to recreate the session.

reopen a new session didn't work for me

**Comment by pan3793** [comment]
@dachn I don't think it's a issue of Kyuubi.

Please provide more details about your case, one phenomenon may be caused by total different reasons, we can do nothing w/o the more information.
