### ISSUE TITLE
[Bug] Invalid engine access token issue

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#2894]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Below exception happen sometimes. Not sure whether the token is lost when establishing the internal connection.
```
java.sql.SQLException: Could not open client transport with JDBC Uri: ****************: org.apache.kyuubi.KyuubiSQLException: Error operating UNKNOWN_OPERATION: org.apache.thrift.transport.TTransportException: Peer indicated failure: PLAIN auth failed: org.apache.kyuubi.KyuubiSQLException: Invalid engine access token
	at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:199)
	at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:307)
	at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37)
	at org.apache.kyuubi.client.KyuubiSyncThriftClient$.createTProtocol(KyuubiSyncThriftClient.scala:396)
	at org.apache.kyuubi.client.KyuubiSyncThriftClient$.createClient(KyuubiSyncThriftClient.scala:414)
	at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1(KyuubiSessionImpl.scala:145)
	at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1$adapted(KyuubiSessionImpl.scala:136)
	at org.apache.kyuubi.ha.client.DiscoveryClientProvider$.withDiscoveryClient(DiscoveryClientProvider.scala:35)
	at org.apache.kyuubi.session.KyuubiSessionImpl.openEngineSession(KyuubiSessionImpl.scala:136)
	at org.apache.kyuubi.operation.LaunchEngine.$anonfun$runInternal$1(LaunchEngine.scala:61)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
	at org.apache.kyuubi.operation.KyuubiOperation$$anonfun$onError$1.applyOrElse(KyuubiOperation.scala:87)
	at org.apache.kyuubi.operation.KyuubiOperation$$anonfun$onError$1.applyOrElse(KyuubiOperation.scala:68)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at org.apache.kyuubi.operation.LaunchEngine.$anonfun$runInternal$1(LaunchEngine.scala:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.transport.TTransportException: Peer indicated failure: PLAIN auth failed: org.apache.kyuubi.KyuubiSQLException: Invalid engine access token
	at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:199)
	at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:307)
	at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37)
	at org.apache.kyuubi.client.KyuubiSyncThriftClient$.createTProtocol(KyuubiSyncThriftClient.scala:396)
	at org.apache.kyuubi.client.KyuubiSyncThriftClient$.createClient(KyuubiSyncThriftClient.scala:414)
	at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1(KyuubiSessionImpl.scala:145)
	at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1$adapted(KyuubiSessionImpl.scala:136)
	at org.apache.kyuubi.ha.client.DiscoveryClientProvider$.withDiscoveryClient(DiscoveryClientProvider.scala:35)
	at org.apache.kyuubi.session.KyuubiSessionImpl.openEngineSession(KyuubiSessionImpl.scala:136)
	at org.apache.kyuubi.operation.LaunchEngine.$anonfun$runInternal$1(LaunchEngine.scala:61)
	... 5 more

	at org.apache.kyuubi.jdbc.hive.KyuubiConnection.<init>(KyuubiConnection.java:227) ~[hive-plugin-1.0.11-jar-with-dependencies.jar.1655093698323:?]
	at org.apache.kyuubi.jdbc.hive.KyuubiConnection.<init>(KyuubiConnection.java:116) ~[hive-plugin-1.0.11-jar-with-dependencies.jar.1655093698323:?]
	at org.apache.kyuubi.jdbc.KyuubiHiveDriver.connect(KyuubiHiveDriver.java:56) ~[hive-plugin-1.0.11-jar-with-dependencies.jar.1655093698323:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_222]
	at java.sql.DriverManager.getConnection(DriverManager.java:270) ~[?:1.8.0_222]
	at com.ebay.dapgap.plugin.hive.policy.impl.GDPRPolicyKyuubiImpl.lambda$getKyuubiConnection$3(GDPRPolicyKyuubiImpl.java:263) ~[hive-plugin-1.0.11-jar-with-dependencies.jar.1655093698323:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_222]
	at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_222]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1888) ~[hadoop-common-2.7.3.2.6.4.2.0.31.jar:?]
	... 15 more
Caused by: java.sql.SQLException: org.apache.kyuubi.KyuubiSQLException: Error operating UNKNOWN_OPERATION: org.apache.thrift.transport.TTransportException: Peer indicated failure: PLAIN auth failed: org.apache.kyuubi.KyuubiSQLException: Invalid engine access token
	at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:199)
	at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:307)
	at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37)
	at org.apache.kyuubi.client.KyuubiSyncThriftClient$.createTProtocol(KyuubiSyncThriftClient.scala:396)
	at org.apache.kyuubi.client.KyuubiSyncThriftClient$.createClient(KyuubiSyncThriftClient.scala:414)
	at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1(KyuubiSessionImpl.scala:145)
	at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1$adapted(KyuubiSessionImpl.scala:136)
	at org.apache.kyuubi.ha.client.DiscoveryClientProvider$.withDiscoveryClient(DiscoveryClientProvider.scala:35)
	at org.apache.kyuubi.session.KyuubiSessionImpl.openEngineSession(KyuubiSessionImpl.scala:136)
	at org.apache.kyuubi.operation.LaunchEngine.$anonfun$runInternal$1(LaunchEngine.scala:61)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
	at org.apache.kyuubi.operation.KyuubiOperation$$anonfun$onError$1.applyOrElse(KyuubiOperation.scala:87)
	at org.apache.kyuubi.operation.KyuubiOperation$$anonfun$onError$1.applyOrElse(KyuubiOperation.scala:68)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at org.apache.kyuubi.operation.LaunchEngine.$anonfun$runInternal$1(LaunchEngine.scala:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.transport.TTransportException: Peer indicated failure: PLAIN auth failed: org.apache.kyuubi.KyuubiSQLException: Invalid engine access token
	at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:199)
	at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:307)
	at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37)
	at org.apache.kyuubi.client.KyuubiSyncThriftClient$.createTProtocol(KyuubiSyncThriftClient.scala:396)
	at org.apache.kyuubi.client.KyuubiSyncThriftClient$.createClient(KyuubiSyncThriftClient.scala:414)
	at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1(KyuubiSessionImpl.scala:145)
	at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1$adapted(KyuubiSessionImpl.scala:136)
	at org.apache.kyuubi.ha.client.DiscoveryClientProvider$.withDiscoveryClient(DiscoveryClientProvider.scala:35)
	at org.apache.kyuubi.session.KyuubiSessionImpl.openEngineSession(KyuubiSessionImpl.scala:136)
	at org.apache.kyuubi.operation.LaunchEngine.$anonfun$runInternal$1(LaunchEngine.scala:61)
	... 5 more

	at org.apache.kyuubi.jdbc.hive.KyuubiConnection.waitLaunchEngineToComplete(KyuubiConnection.java:1751) ~[hive-plugin-1.0.11-jar-with-dependencies.jar.1655093698323:?]
	at org.apache.kyuubi.jdbc.hive.KyuubiConnection.<init>(KyuubiConnection.java:201) ~[hive-plugin-1.0.11-jar-with-dependencies.jar.1655093698323:?]
	at org.apache.kyuubi.jdbc.hive.KyuubiConnection.<init>(KyuubiConnection.java:116) ~[hive-plugin-1.0.11-jar-with-dependencies.jar.1655093698323:?]
	at org.apache.kyuubi.jdbc.KyuubiHiveDriver.connect(KyuubiHiveDriver.java:56) ~[hive-plugin-1.0.11-jar-with-dependencies.jar.1655093698323:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_222]
	at java.sql.DriverManager.getConnection(DriverManager.java:270) ~[?:1.8.0_222]
	at com.ebay.dapgap.plugin.hive.policy.impl.GDPRPolicyKyuubiImpl.lambda$getKyuubiConnection$3(GDPRPolicyKyuubiImpl.java:263) ~[hive-plugin-1.0.11-jar-with-dependencies.jar.1655093698323:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_222]
	at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_222]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1888) ~[hadoop-common-2.7.3.2.6.4.2.0.31.jar:?]
	... 15 more
```

### Affects Version(s)

1.6.0

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by turboFei** [comment]
I plan to add more log info in ebay kyuubi.
