### ISSUE TITLE
Flaky Test: KyuubiOperationThriftHttpKerberosAndPlainAuthSuite - test with LDAP authentication

### ISSUE THREAD

**Issue by cxzl25** [apache/incubator-kyuubi#2907]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

```
KyuubiOperationThriftHttpKerberosAndPlainAuthSuite:
- test with LDAP authentication *** FAILED ***
  java.sql.SQLException: Could not open client transport with JDBC Uri: jdbc:hive2://localhost:10010/default;transportMode=http;httpPath=cliservice: Could not establish connection to jdbc:hive2://localhost:10010/default;transportMode=http;httpPath=cliservice: org.apache.kyuubi.shade.org.apache.http.conn.HttpHostConnectException: Connect to localhost:10010 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
  at org.apache.kyuubi.jdbc.hive.KyuubiConnection.<init>(KyuubiConnection.java:232)
  at org.apache.kyuubi.jdbc.KyuubiHiveDriver.connect(KyuubiHiveDriver.java:59)
  at java.sql.DriverManager.getConnection(DriverManager.java:664)
  at java.sql.DriverManager.getConnection(DriverManager.java:247)
  at org.apache.kyuubi.operation.KyuubiOperationKerberosAndPlainAuthSuite.$anonfun$new$2(KyuubiOperationKerberosAndPlainAuthSuite.scala:81)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  ...
  Cause: java.sql.SQLException: Could not establish connection to jdbc:hive2://localhost:10010/default;transportMode=http;httpPath=cliservice: org.apache.kyuubi.shade.org.apache.http.conn.HttpHostConnectException: Connect to localhost:10010 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
  at org.apache.kyuubi.jdbc.hive.KyuubiConnection.openSession(KyuubiConnection.java:853)
  at org.apache.kyuubi.jdbc.hive.KyuubiConnection.<init>(KyuubiConnection.java:198)
  at org.apache.kyuubi.jdbc.KyuubiHiveDriver.connect(KyuubiHiveDriver.java:59)
  at java.sql.DriverManager.getConnection(DriverManager.java:664)
  at java.sql.DriverManager.getConnection(DriverManager.java:247)
  at org.apache.kyuubi.operation.KyuubiOperationKerberosAndPlainAuthSuite.$anonfun$new$2(KyuubiOperationKerberosAndPlainAuthSuite.scala:81)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  ...
  Cause: org.apache.kyuubi.shade.org.apache.thrift.transport.TTransportException: org.apache.kyuubi.shade.org.apache.http.conn.HttpHostConnectException: Connect to localhost:10010 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
  at org.apache.kyuubi.shade.org.apache.thrift.transport.THttpClient.flushUsingHttpClient(THttpClient.java:297)
  at org.apache.kyuubi.shade.org.apache.thrift.transport.THttpClient.flush(THttpClient.java:313)
  at org.apache.kyuubi.shade.org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:73)
  at org.apache.kyuubi.shade.org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
  at org.apache.kyuubi.shade.org.apache.hive.service.rpc.thrift.TCLIService$Client.send_OpenSession(TCLIService.java:170)
  at org.apache.kyuubi.shade.org.apache.hive.service.rpc.thrift.TCLIService$Client.OpenSession(TCLIService.java:162)
  at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.apache.kyuubi.jdbc.hive.KyuubiConnection$SynchronizedHandler.invoke(KyuubiConnection.java:1289)
  ...
  Cause: org.apache.kyuubi.shade.org.apache.http.conn.HttpHostConnectException: Connect to localhost:10010 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
  at org.apache.kyuubi.shade.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
  at org.apache.kyuubi.shade.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
  at org.apache.kyuubi.shade.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
  at org.apache.kyuubi.shade.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
  at org.apache.kyuubi.shade.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
  at org.apache.kyuubi.shade.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
  at org.apache.kyuubi.shade.org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85)
  at org.apache.kyuubi.shade.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
  at org.apache.kyuubi.shade.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
  at org.apache.kyuubi.shade.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
  ...
  Cause: java.net.ConnectException: Connection refused (Connection refused)
  at java.net.PlainSocketImpl.socketConnect(Native Method)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  at java.net.Socket.connect(Socket.java:613)
  at org.apache.kyuubi.shade.org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
  at org.apache.kyuubi.shade.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
  at org.apache.kyuubi.shade.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
  at org.apache.kyuubi.shade.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
  ...
```

### Actions URL

https://github.com/apache/incubator-kyuubi/actions/runs/2516619438
https://github.com/apache/incubator-kyuubi/runs/6939183651?check_suite_focus=true

### Parent issue

#1733

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ulysses-you** [comment]
seems it's very flaky.. cc @turboFei

**Comment by turboFei** [comment]
Maybe ThriftHttpServlet does not follow the behavior of AuthenticationFilter.
