### ISSUE TITLE
[Bug] The spark engine cannot exit because the zookeeper delete operation waits indefinitely.

### ISSUE THREAD

**Issue by wForget** [apache/incubator-kyuubi#3492]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

The spark engine started on June 24 has not quit so far, because the zookeeper delete operation waits indefinitely.

```
"Thread-3" #25 prio=5 os_prio=0 tid=0x00000000038a2000 nid=0x24af6c waiting for monitor entry [0x00007f40aab40000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.apache.kyuubi.service.Serverable.stop(Serverable.scala:59)
	- waiting to lock <0x0000000701c06d78> (a org.apache.kyuubi.engine.spark.SparkSQLEngine)
	at org.apache.kyuubi.engine.spark.SparkSQLEngine$.$anonfun$startEngine$4(SparkSQLEngine.scala:145)
	at org.apache.kyuubi.engine.spark.SparkSQLEngine$$$Lambda$1981/320334104.run(Unknown Source)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:54)

```

```
"SparkThriftBinaryFrontendServiceHandler-Pool: Thread-344" #344 prio=5 os_prio=0 tid=0x00007f40c4ad1800 nid=0x206a35 in Object.wait() [0x00007f40a60c1000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1407)
	- locked <0x0000000702a6a6b8> (a org.apache.zookeeper.ClientCnxn$Packet)
	at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:880)
	at org.apache.kyuubi.shade.org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:250)
	at org.apache.kyuubi.shade.org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:244)
	at org.apache.kyuubi.shade.org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
	at org.apache.kyuubi.shade.org.apache.curator.framework.imps.DeleteBuilderImpl.pathInForeground(DeleteBuilderImpl.java:241)
	at org.apache.kyuubi.shade.org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:225)
	at org.apache.kyuubi.shade.org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:35)
	at org.apache.kyuubi.shade.org.apache.curator.framework.recipes.nodes.PersistentNode.deleteNode(PersistentNode.java:347)
	at org.apache.kyuubi.shade.org.apache.curator.framework.recipes.nodes.PersistentNode.close(PersistentNode.java:291)
	at org.apache.kyuubi.ha.client.ServiceDiscovery.closeServiceNode(ServiceDiscovery.scala:127)
	at org.apache.kyuubi.ha.client.EngineServiceDiscovery.stop(EngineServiceDiscovery.scala:34)
	- locked <0x0000000701c07328> (a org.apache.kyuubi.ha.client.EngineServiceDiscovery)
	at org.apache.kyuubi.service.CompositeService.$anonfun$stop$2(CompositeService.scala:75)
	at org.apache.kyuubi.service.CompositeService.$anonfun$stop$2$adapted(CompositeService.scala:72)
	at org.apache.kyuubi.service.CompositeService$$Lambda$3350/181028072.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.kyuubi.service.CompositeService.stop(CompositeService.scala:72)
	at org.apache.kyuubi.service.CompositeService.stop(CompositeService.scala:61)
	at org.apache.kyuubi.service.ThriftBinaryFrontendService.stop(ThriftBinaryFrontendService.scala:146)
	- locked <0x0000000701c07118> (a org.apache.kyuubi.engine.spark.SparkThriftBinaryFrontendService)
	at org.apache.kyuubi.service.CompositeService.$anonfun$stop$2(CompositeService.scala:75)
	at org.apache.kyuubi.service.CompositeService.$anonfun$stop$2$adapted(CompositeService.scala:72)
	at org.apache.kyuubi.service.CompositeService$$Lambda$3350/181028072.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.kyuubi.service.CompositeService.stop(CompositeService.scala:72)
	at org.apache.kyuubi.service.CompositeService.stop(CompositeService.scala:61)
	at org.apache.kyuubi.service.Serverable.stop(Serverable.scala:60)
	- locked <0x0000000701c06d78> (a org.apache.kyuubi.engine.spark.SparkSQLEngine)
	at org.apache.kyuubi.engine.spark.session.SparkSQLSessionManager.$anonfun$stopSession$1(SparkSQLSessionManager.scala:119)
	at org.apache.kyuubi.engine.spark.session.SparkSQLSessionManager.$anonfun$stopSession$1$adapted(SparkSQLSessionManager.scala:119)
	at org.apache.kyuubi.engine.spark.session.SparkSQLSessionManager$$Lambda$3349/90060495.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.kyuubi.engine.spark.session.SparkSQLSessionManager.stopSession(SparkSQLSessionManager.scala:119)
	at org.apache.kyuubi.engine.spark.session.SparkSQLSessionManager.closeSession(SparkSQLSessionManager.scala:105)
	at org.apache.kyuubi.service.AbstractBackendService.closeSession(AbstractBackendService.scala:49)
	at org.apache.kyuubi.service.ThriftBinaryFrontendService$FeTServerEventHandler.deleteContext(ThriftBinaryFrontendService.scala:539)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### Affects Version(s)

1.4.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wForget** [comment]
There are OutOfMemory errors in log:

```
java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by wForget** [comment]
Recently, I have added OutOfMemory hook, close this issue first.

```
spark.driver.extraJavaOptions   -XX:OnOutOfMemoryError='kill %p'
```
