### ISSUE TITLE
[Bug] Reading an uninitialized log should return empty rowSet

### ISSUE THREAD

**Issue by yikf** [apache/incubator-kyuubi#3510]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Reading an uninitialized log should return empty rowSet , So we can set `EmptyRowSet` for `TFetchResultsResp` to avoid client side NPE if FetchResults fail on server side.

Configure log4j for `ERROR` level, causing the engine side no log file output, so server side throw `java.nio.file. NoSuchFileException`, at this time the client get engine log, throws the NPE.

### Affects Version(s)

1.6.0

### Kyuubi Server Log Output

```logtalk
beeline> !connect jdbc:hive2://B000000335049P:10009/
Connecting to jdbc:hive2://B000000335049P:10009/
Enter username for jdbc:hive2://B000000335049P:10009/:
Enter password for jdbc:hive2://B000000335049P:10009/:
Exception in thread "Thread-3" java.lang.NullPointerException
	at org.apache.kyuubi.jdbc.hive.cli.ColumnBasedSet.<init>(ColumnBasedSet.java:43)
	at org.apache.kyuubi.jdbc.hive.cli.RowSetFactory.create(RowSetFactory.java:31)
	at org.apache.kyuubi.jdbc.hive.KyuubiConnection.getExecLog(KyuubiConnection.java:270)
	at org.apache.hive.beeline.KyuubiCommands.showRemainingLogsIfAny(KyuubiCommands.java:389)
	at org.apache.hive.beeline.KyuubiCommands.access$000(KyuubiCommands.java:30)
	at org.apache.hive.beeline.KyuubiCommands$KyuubiLogRunnable.run(KyuubiCommands.java:559)
	at java.lang.Thread.run(Thread.java:748)
21:56:12.086 [main] ERROR org.apache.kyuubi.jdbc.hive.KyuubiConnection - Error fetching launch engine result
java.lang.NullPointerException: null
	at org.apache.kyuubi.jdbc.hive.cli.ColumnBasedSet.<init>(ColumnBasedSet.java:43) ~[kyuubi-hive-jdbc-1.7.0-SNAPSHOT.jar:1.7.0-SNAPSHOT]
	at org.apache.kyuubi.jdbc.hive.cli.RowSetFactory.create(RowSetFactory.java:31) ~[kyuubi-hive-jdbc-1.7.0-SNAPSHOT.jar:1.7.0-SNAPSHOT]
	at org.apache.kyuubi.jdbc.hive.KyuubiConnection.fetchLaunchEngineResult(KyuubiConnection.java:1337) ~[kyuubi-hive-jdbc-1.7.0-SNAPSHOT.jar:1.7.0-SNAPSHOT]
	at org.apache.kyuubi.jdbc.hive.KyuubiConnection.waitLaunchEngineToComplete(KyuubiConnection.java:1292) ~[kyuubi-hive-jdbc-1.7.0-SNAPSHOT.jar:1.7.0-SNAPSHOT]
	at org.apache.hive.beeline.KyuubiDatabaseConnection.getConnectionFromDefaultDriver(KyuubiDatabaseConnection.java:145) ~[kyuubi-hive-beeline-1.6.0-incubating.jar:1.6.0-incubating]
	at org.apache.hive.beeline.KyuubiDatabaseConnection.connect(KyuubiDatabaseConnection.java:91) ~[kyuubi-hive-beeline-1.6.0-incubating.jar:1.6.0-incubating]
	at org.apache.hive.beeline.DatabaseConnection.getConnection(DatabaseConnection.java:209) ~[hive-beeline-3.1.3.jar:1.6.0-incubating]
	at org.apache.hive.beeline.KyuubiDatabaseConnection.getConnection(KyuubiDatabaseConnection.java:28) ~[kyuubi-hive-beeline-1.6.0-incubating.jar:1.6.0-incubating]
	at org.apache.hive.beeline.KyuubiCommands.connect(KyuubiCommands.java:492) ~[kyuubi-hive-beeline-1.6.0-incubating.jar:1.6.0-incubating]
	at org.apache.hive.beeline.Commands.connect(Commands.java:1536) ~[hive-beeline-3.1.3.jar:1.6.0-incubating]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.apache.hive.beeline.ReflectiveCommandHandler.execute(ReflectiveCommandHandler.java:56) ~[hive-beeline-3.1.3.jar:1.6.0-incubating]
	at org.apache.hive.beeline.BeeLine.execCommandWithPrefix(BeeLine.java:1384) ~[hive-beeline-3.1.3.jar:1.6.0-incubating]
	at org.apache.hive.beeline.BeeLine.dispatch(BeeLine.java:1423) ~[hive-beeline-3.1.3.jar:1.6.0-incubating]
	at org.apache.hive.beeline.BeeLine.execute(BeeLine.java:1287) ~[hive-beeline-3.1.3.jar:1.6.0-incubating]
	at org.apache.hive.beeline.BeeLine.begin(BeeLine.java:1071) ~[hive-beeline-3.1.3.jar:1.6.0-incubating]
	at org.apache.hive.beeline.KyuubiBeeLine.mainWithInputRedirection(KyuubiBeeLine.java:82) ~[kyuubi-hive-beeline-1.6.0-incubating.jar:1.6.0-incubating]
	at org.apache.hive.beeline.KyuubiBeeLine.main(KyuubiBeeLine.java:67) ~[kyuubi-hive-beeline-1.6.0-incubating.jar:1.6.0-incubating]
Connected to: Apache Kyuubi (Incubating) (version 1.6.0-incubating)
Driver: Kyuubi Project Hive JDBC Client (version 1.7.0-SNAPSHOT)
```

### Are you willing to submit PR?

- [X] Yes. I can submit a PR independently to fix.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Related to https://github.com/apache/incubator-kyuubi/pull/2296 cc @ulysses-you
