### ISSUE TITLE
[Bug] Unsupported mechanism type PLAIN

### ISSUE THREAD

**Issue by zzzzming95** [apache/incubator-kyuubi#3525]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

I have a kerberos environment and have the following kerberos related configurations configured in kyuubi-default.xml:
```
kyuubi.authentication           KERBEROS
kyuubi.kinit.principal          hive/testhost@TEST.com
kyuubi.kinit.keytab             keytab_absolute_path

```

When I use beeline to connect, I get the following error:

> beeline -u "jdbc:hive2://host:10009/;principal=hive/testhost@TEST.com;hive.server2.proxy.user=hive/testhost@TEST.com"

I get error as below

```
/home/hadoop/spark-3.2.2_GDC_V1.0.0-bin-hadoop-3.3.0-release/bin/spark-submit \
    --class org.apache.kyuubi.engine.spark.SparkSQLEngine \
    --conf spark.kyuubi.session.engine.initialize.timeout=90000 \
    --conf spark.kyuubi.ha.zookeeper.quorum=zk_host:2181 \
    --conf spark.kyuubi.engine.submit.time=1663599145081 \
    --conf spark.app.name=job_name \
    --conf spark.kyuubi.ha.engine.ref.id=b2df62c2-8188-40ec-b08f-089e40e50ab0 \
    --conf spark.hive.server2.proxy.user=hive/testhost@TEST.com \
    --conf spark.kyuubi.engine.credentials=xxxR0FUSU9OX1RPS0VOD2hhLWhkZnM6cmVkcG9sbAA= \
    --conf spark.yarn.tags=KYUUBI,b2df62c2-8188-40ec-b08f-089e40e50ab0 \
    --conf spark.kyuubi.client.ipAddress=kyuubi_host \
    --conf spark.kyuubi.ha.namespace=/path \
    --proxy-user hive/testhost@TEST.com /home/hadoop/apache-kyuubi-1.6.0-incubating-bin/externals/engines/spark/kyuubi-spark-sql-engine_2.12-1.6.0-incubating.jar

......
2022-09-19 22:52:59.344 ERROR org.apache.kyuubi.session.KyuubiSessionImpl: Opening engine [kyuubi_USER_SPARK_SQL_hadoop/nn@NIE.NETEASE.COM_default_b2df62c2-8188-40ec-b08f-089e40e50ab0 gdc-sparkserver07-fenghuang.i.nease.net:32737] for hadoop/nn@NIE.NETEASE.COM session failed
org.apache.thrift.transport.TTransportException: Peer indicated failure: Unsupported mechanism type PLAIN
    at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:199) ~[libthrift-0.9.3.jar:0.9.3]
    at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:307) ~[libthrift-0.9.3.jar:0.9.3]
    at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37) ~[libthrift-0.9.3.jar:0.9.3]
    at org.apache.kyuubi.client.KyuubiSyncThriftClient$.createTProtocol(KyuubiSyncThriftClient.scala:448) ~[kyuubi-server_2.12-1.6.0-incubating.jar:1.6.0-incubating]
    at org.apache.kyuubi.client.KyuubiSyncThriftClient$.createClient(KyuubiSyncThriftClient.scala:464) ~[kyuubi-server_2.12-1.6.0-incubating.jar:1.6.0-incubating]
    at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1(KyuubiSessionImpl.scala:127) ~[kyuubi-server_2.12-1.6.0-incubating.jar:1.6.0-incubating]
    at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1$adapted(KyuubiSessionImpl.scala:112) ~[kyuubi-server_2.12-1.6.0-incubating.jar:1.6.0-incubating]
    at org.apache.kyuubi.ha.client.DiscoveryClientProvider$.withDiscoveryClient(DiscoveryClientProvider.scala:36) ~[kyuubi-ha_2.12-1.6.0-incubating.jar:1.6.0-incubating]
    at org.apache.kyuubi.session.KyuubiSessionImpl.openEngineSession(KyuubiSessionImpl.scala:112) ~[kyuubi-server_2.12-1.6.0-incubating.jar:1.6.0-incubating]
    at org.apache.kyuubi.operation.LaunchEngine.$anonfun$runInternal$2(LaunchEngine.scala:49) ~[kyuubi-server_2.12-1.6.0-incubating.jar:1.6.0-incubating]

```

Then I found that when connecting kyuubi-engine in `KyuubiSessionImpl#openEngineSession`, there is indeed only PLAIN authentication method, resulting in an error

https://github.com/apache/incubator-kyuubi/blob/73612b7750264b6d43e48ee0277a89bd9de0b82a/kyuubi-server/src/main/scala/org/apache/kyuubi/client/KyuubiSyncThriftClient.scala#L465

Am I missing some parameter configuration?

### Affects Version(s)

1.6.0

### Kyuubi Server Log Output

```logtalk
2022-09-19 22:52:59.344 ERROR org.apache.kyuubi.session.KyuubiSessionImpl: Opening engine [kyuubi_USER_SPARK_SQL_hadoop/nn@NIE.NETEASE.COM_default_b2df62c2-8188-40ec-b08f-089e40e50ab0 gdc-sparkserver07-fenghuang.i.nease.net:32737] for hadoop/nn@NIE.NETEASE.COM session failed
org.apache.thrift.transport.TTransportException: Peer indicated failure: Unsupported mechanism type PLAIN
    at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:199) ~[libthrift-0.9.3.jar:0.9.3]
    at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:307) ~[libthrift-0.9.3.jar:0.9.3]
    at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37) ~[libthrift-0.9.3.jar:0.9.3]
    at org.apache.kyuubi.client.KyuubiSyncThriftClient$.createTProtocol(KyuubiSyncThriftClient.scala:448) ~[kyuubi-server_2.12-1.6.0-incubating.jar:1.6.0-incubating]
    at org.apache.kyuubi.client.KyuubiSyncThriftClient$.createClient(KyuubiSyncThriftClient.scala:464) ~[kyuubi-server_2.12-1.6.0-incubating.jar:1.6.0-incubating]
    at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1(KyuubiSessionImpl.scala:127) ~[kyuubi-server_2.12-1.6.0-incubating.jar:1.6.0-incubating]
    at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1$adapted(KyuubiSessionImpl.scala:112) ~[kyuubi-server_2.12-1.6.0-incubating.jar:1.6.0-incubating]
    at org.apache.kyuubi.ha.client.DiscoveryClientProvider$.withDiscoveryClient(DiscoveryClientProvider.scala:36) ~[kyuubi-ha_2.12-1.6.0-incubating.jar:1.6.0-incubating]
    at org.apache.kyuubi.session.KyuubiSessionImpl.openEngineSession(KyuubiSessionImpl.scala:112) ~[kyuubi-server_2.12-1.6.0-incubating.jar:1.6.0-incubating]
    at org.apache.kyuubi.operation.LaunchEngine.$anonfun$runInternal$2(LaunchEngine.scala:49) ~[kyuubi-server_2.12-1.6.0-incubating.jar:1.6.0-incubating]
```

### Kyuubi Engine Log Output

```logtalk
java.lang.RuntimeException: org.apache.kyuubi.shade.org.apache.thrift.transport.TTransportException: Unsupported mechanism type PLAIN
    at org.apache.kyuubi.shade.org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:219)
    at org.apache.kyuubi.service.authentication.HadoopThriftAuthBridgeServer$TUGIAssumingTransportFactory$$anon$4.run(HadoopThriftAuthBridgeServer.scala:117)
    at org.apache.kyuubi.service.authentication.HadoopThriftAuthBridgeServer$TUGIAssumingTransportFactory$$anon$4.run(HadoopThriftAuthBridgeServer.scala:116)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:360)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1722)
    at org.apache.kyuubi.service.authentication.HadoopThriftAuthBridgeServer$TUGIAssumingTransportFactory.getTransport(HadoopThriftAuthBridgeServer.scala:116)
    at org.apache.kyuubi.shade.org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:269)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kyuubi.shade.org.apache.thrift.transport.TTransportException: Unsupported mechanism type PLAIN
    at org.apache.kyuubi.shade.org.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:232)
    at org.apache.kyuubi.shade.org.apache.thrift.transport.TSaslServerTransport.handleSaslStartMessage(TSaslServerTransport.java:138)
    at org.apache.kyuubi.shade.org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:271)
    at org.apache.kyuubi.shade.org.apache.thrift.transport.TSaslServerTransport.open(TSaslServerTransport.java:41)
```

### Kyuubi Server Configurations

```yaml
kyuubi.authentication           KERBEROS
kyuubi.kinit.principal          hive/testhost@TEST.com
kyuubi.kinit.keytab             keytab_absolute_path
```

### Are you willing to submit PR?

- [X] Yes. I can submit a PR independently to fix.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Do you put the following configuration to the `spark-defaults.conf`?
```
kyuubi.authentication           KERBEROS
```
