### ISSUE TITLE
[Bug] User and Connection switch login lock

### ISSUE THREAD

**Issue by wangmiao1002** [apache/incubator-kyuubi#3754]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

There is a lock displayed on the zk, unable to log in

### Affects Version(s)

1.5.2

### Kyuubi Server Log Output

```logtalk
java.util.concurrent.ExecutionException: org.apache.kyuubi.KyuubiSQLException: Timeout to lock on path [/kyuubi_USER/lock/hive/default] after 180000 ms. There would be some p
roblem that other session may create engine timeout.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_141]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_141]
        at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$waitForEngineLaunched$1(KyuubiSessionImpl.scala:131) ~[kyuubi-server_2.12-1.5.2-incubating.jar:1.5.2-incubatin
g]
        at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$waitForEngineLaunched$1$adapted(KyuubiSessionImpl.scala:127) ~[kyuubi-server_2.12-1.5.2-incubating.jar:1.5.2-i
ncubating]
        at scala.Option.foreach(Option.scala:407) ~[scala-library-2.12.15.jar:?]
        at org.apache.kyuubi.session.KyuubiSessionImpl.waitForEngineLaunched(KyuubiSessionImpl.scala:127) ~[kyuubi-server_2.12-1.5.2-incubating.jar:1.5.2-incubating]
        at org.apache.kyuubi.session.KyuubiSessionImpl.runOperation(KyuubiSessionImpl.scala:117) ~[kyuubi-server_2.12-1.5.2-incubating.jar:1.5.2-incubating]
        at org.apache.kyuubi.session.AbstractSession.$anonfun$executeStatement$1(AbstractSession.scala:124) ~[kyuubi-common_2.12-1.5.2-incubating.jar:1.5.2-incubating]
        at org.apache.kyuubi.session.AbstractSession.withAcquireRelease(AbstractSession.scala:75) ~[kyuubi-common_2.12-1.5.2-incubating.jar:1.5.2-incubating]
        at org.apache.kyuubi.session.AbstractSession.executeStatement(AbstractSession.scala:121) ~[kyuubi-common_2.12-1.5.2-incubating.jar:1.5.2-incubating]
        at org.apache.kyuubi.service.AbstractBackendService.executeStatement(AbstractBackendService.scala:66) ~[kyuubi-common_2.12-1.5.2-incubating.jar:1.5.2-incubating]
        at org.apache.kyuubi.server.KyuubiServer$$anon$1.org$apache$kyuubi$server$BackendServiceMetric$$super$executeStatement(KyuubiServer.scala:142) ~[kyuubi-server_2.12-1.
5.2-incubating.jar:1.5.2-incubating]
        at org.apache.kyuubi.server.BackendServiceMetric.$anonfun$executeStatement$1(BackendServiceMetric.scala:62) ~[kyuubi-server_2.12-1.5.2-incubating.jar:1.5.2-incubating
]
        at org.apache.kyuubi.metrics.MetricsSystem$.timerTracing(MetricsSystem.scala:111) ~[kyuubi-metrics_2.12-1.5.2-incubating.jar:1.5.2-incubating]
        at org.apache.kyuubi.server.BackendServiceMetric.executeStatement(BackendServiceMetric.scala:62) ~[kyuubi-server_2.12-1.5.2-incubating.jar:1.5.2-incubating]
        at org.apache.kyuubi.server.BackendServiceMetric.executeStatement$(BackendServiceMetric.scala:55) ~[kyuubi-server_2.12-1.5.2-incubating.jar:1.5.2-incubating]
        at org.apache.kyuubi.server.KyuubiServer$$anon$1.executeStatement(KyuubiServer.scala:142) ~[kyuubi-server_2.12-1.5.2-incubating.jar:1.5.2-incubating]
        at org.apache.kyuubi.service.TFrontendService.ExecuteStatement(TFrontendService.scala:232) ~[kyuubi-common_2.12-1.5.2-incubating.jar:1.5.2-incubating]
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1557) ~[hive-service-rpc-3.1.2.jar:3.1.2]
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1542) ~[hive-service-rpc-3.1.2.jar:3.1.2]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) ~[libthrift-0.9.3.jar:0.9.3]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) ~[libthrift-0.9.3.jar:0.9.3]
        at org.apache.kyuubi.service.authentication.TSetIpAddressProcessor.process(TSetIpAddressProcessor.scala:36) ~[kyuubi-common_2.12-1.5.2-incubating.jar:1.5.2-incubating
]
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) ~[libthrift-0.9.3.jar:0.9.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_141]
```

### Are you willing to submit PR?

- [X] Yes. I can submit a PR independently to fix.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
The stack trace indicates that another connection of user `hive` holds the zk lock for more than 180s, it may be caused by user `hive` creating multi connections at the same time, and only one got the lock but stuck on `spark-submit`, you should check the log context to get more information.

**Comment by wangmiao1002** [comment]
> The stack trace indicates that another connection of user `hive` holds the zk lock for more than 180s, it may be caused by user `hive` creating multi connections at the same time, and only one got the lock but stuck on `spark-submit`, you should check the log context to get more information.

Thank you for your reply. It is true that the client will create multiple connections when connecting. Please check the specific reasons.

**Comment by serge1994** [comment]
@wangmiao1002 Has this issue been fixed?
