### ISSUE TITLE
[Bug] bin/kyuubi restart fail when using embeded zookeeper

### ISSUE THREAD

**Issue by baiyangtx** [apache/incubator-kyuubi#3829]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

if using embedded zookeeper,  bash script `bin/kyuubi restart`  will failed for reason ` java.net.BindException: Address already in use`

### Affects Version(s)

1.6.0

### Kyuubi Server Log Output

```logtalk
2022-11-22 15:43:56.806 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:os.version=3.10.0-862.el7.x86_64
2022-11-22 15:43:56.806 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:user.name=hdfs
2022-11-22 15:43:56.806 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:user.home=/home/hdfs
2022-11-22 15:43:56.806 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:user.dir=/home/hdfs/apache-kyuubi-1.6.0-incubating-bin
2022-11-22 15:43:56.826 INFO org.apache.zookeeper.server.ZooKeeperServer: Created server with tickTime 3000 minSessionTimeout 6000 maxSessionTimeout 60000 datadir embedded_zookeeper/version-2 snapdir embedded_zookeeper/version-2
2022-11-22 15:43:56.826 INFO org.apache.zookeeper.server.ZooKeeperServer: minSessionTimeout set to 6000
2022-11-22 15:43:56.826 INFO org.apache.zookeeper.server.ZooKeeperServer: maxSessionTimeout set to 60000
2022-11-22 15:43:56.841 INFO org.apache.zookeeper.server.NIOServerCnxnFactory: binding to port sloth-commerce-test2.jd.163.org/10.196.98.26:2188
Exception in thread "main" java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
        at org.apache.zookeeper.server.NIOServerCnxnFactory.configure(NIOServerCnxnFactory.java:90)
        at org.apache.kyuubi.zookeeper.EmbeddedZookeeper.initialize(EmbeddedZookeeper.scala:53)
        at org.apache.kyuubi.server.KyuubiServer$.startServer(KyuubiServer.scala:45)
        at org.apache.kyuubi.server.KyuubiServer$.main(KyuubiServer.scala:93)
        at org.apache.kyuubi.server.KyuubiServer.main(KyuubiServer.scala)
```

### Kyuubi Server Configurations

```yaml
kyuubi.zookeeper.embedded.port=2188
```

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to fix.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Please try 1.6.1, https://github.com/apache/incubator-kyuubi/issues/3544 may fix this issue

**Comment by pan3793** [comment]
Close as duplicated, feel free to reopen if you still encounter this issue w/ 1.6.1+ versions
