### ISSUE TITLE
[TEST] the new client should work properly when the engine exits unexpectedly *** FAILED ***

### ISSUE THREAD

**Issue by cxzl25** [apache/incubator-kyuubi#3909]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What kind of test improve?

- [X] Fix flaky tests.
- [ ] Fix bug in tests.
- [ ] Increase test coverage.
- [ ] Other kinds of test improve.

### Describe the issues of the existing tests or improvements for new tests

https://github.com/apache/incubator-kyuubi/actions/runs/3625859230/jobs/6114323952

```java
- the new client should work properly when the engine exits unexpectedly *** FAILED ***
  org.apache.thrift.protocol.TProtocolException: Required field 'operationHandle' is unset! Struct:TGetOperationStatusReq(operationHandle:null)
  at org.apache.hive.service.rpc.thrift.TGetOperationStatusReq.validate(TGetOperationStatusReq.java:373)
  at org.apache.hive.service.rpc.thrift.TCLIService$GetOperationStatus_args.validate(TCLIService.java:12851)
  at org.apache.hive.service.rpc.thrift.TCLIService$GetOperationStatus_args$GetOperationStatus_argsStandardScheme.write(TCLIService.java:12908)
  at org.apache.hive.service.rpc.thrift.TCLIService$GetOperationStatus_args$GetOperationStatus_argsStandardScheme.write(TCLIService.java:12877)
  at org.apache.hive.service.rpc.thrift.TCLIService$GetOperationStatus_args.write(TCLIService.java:12828)
  at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:71)
  at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
  at org.apache.hive.service.rpc.thrift.TCLIService$Client.send_GetOperationStatus(TCLIService.java:469)
  at org.apache.hive.service.rpc.thrift.TCLIService$Client.GetOperationStatus(TCLIService.java:461)
  at org.apache.kyuubi.operation.HiveJDBCTestHelper.waitForOperationToComplete(HiveJDBCTestHelper.scala:116)
```

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by cxzl25** [comment]
KyuubiOperationPerUserSuite
```scala
  test("the new client should work properly when the engine exits unexpectedly") {

        val exitReq = new TExecuteStatementReq()
        // force kill engine without shutdown hook
        exitReq.setStatement("java.lang.Runtime.getRuntime().halt(-1)")
        exitReq.setSessionHandle(handle)
        exitReq.setRunAsync(true)
        client.ExecuteStatement(exitReq)
```

In PR #3884 we support scala async.
