### ISSUE TITLE
[TEST] KYUUBI #3839 session user sign - check session user sign *** FAILED ***

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#3930]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What kind of test improve?

- [X] Fix flaky tests.
- [ ] Fix bug in tests.
- [ ] Increase test coverage.
- [ ] Other kinds of test improve.

### Describe the issues of the existing tests or improvements for new tests

https://github.com/apache/incubator-kyuubi/actions/runs/3637051754/jobs/6137647175
```
- KYUUBI #3839 session user sign - check session user sign *** FAILED ***
  java.lang.IllegalArgumentException: Illegal base64 character 2a
  at java.base/java.util.Base64$Decoder.decode0(Base64.java:746)
  at java.base/java.util.Base64$Decoder.decode(Base64.java:538)
  at java.base/java.util.Base64$Decoder.decode(Base64.java:561)
  at org.apache.kyuubi.util.SignUtils$.verifySignWithECDSA(SignUtils.scala:64)
  at org.apache.kyuubi.session.SessionSigningSuite.$anonfun$new$10(SessionSigningSuite.scala:81)
  at org.apache.kyuubi.session.SessionSigningSuite.$anonfun$new$10$adapted(SessionSigningSuite.scala:70)
  at org.apache.kyuubi.operation.JDBCTestHelper.$anonfun$withMultipleConnectionJdbcStatement$3(JDBCTestHelper.scala:60)
  at org.apache.kyuubi.operation.JDBCTestHelper.$anonfun$withMultipleConnectionJdbcStatement$3$adapted(JDBCTestHelper.scala:60)
  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
```

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by turboFei** [comment]
cc @bowenliang123

**Comment by bowenliang123** [comment]
Mark From pull https://github.com/apache/incubator-kyuubi/pull/3923

**Comment by turboFei** [comment]
As discussed offkine， you can check whether there's thread safe issue.

**Comment by turboFei** [comment]
Maybe similar with #2933

**Comment by bowenliang123** [comment]
cc @cfmcgrady
