### ISSUE TITLE
Fix KyuubiDriverSuite UT failure because of NPE

### ISSUE THREAD

**Issue by yanghua** [apache/incubator-kyuubi#817]
### 1. Describe the bug

Run `KyuubiDriverSuite` in my local IDE, but failed because of NPE(missing kyuubi-version-info.properties).

### 2. Environments

- Mac OS X 10.14.5
- Intellij IDEA 19.2
- Java 1.8

#### 2.1 Versions

- Kyuubi
  - [x] 1.13.0(master)
  - [ ] 1.0.3
  - [ ] 0.8.x and earlier 

- Spark
  - [ ] 3.1.x
  - [ ] 3.0.x
  - [x] 2.4.x and earlier 

#### 2.2 Kyuubi Configurations

none(local UT)

#### 2.3 Spark Configurations

none(local UT)

### 4. Additional context

```
An exception or error caused a run to abort: Failed to initialize frontend service on /127.0.0.1:0. 
org.apache.kyuubi.KyuubiException: Failed to initialize frontend service on /127.0.0.1:0.
	at org.apache.kyuubi.service.FrontendService.initialize(FrontendService.scala:102)
	at org.apache.kyuubi.service.CompositeService.$anonfun$initialize$1(CompositeService.scala:40)
	at org.apache.kyuubi.service.CompositeService.$anonfun$initialize$1$adapted(CompositeService.scala:40)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.kyuubi.service.CompositeService.initialize(CompositeService.scala:40)
	at org.apache.kyuubi.service.Serverable.initialize(Serverable.scala:44)
	at org.apache.kyuubi.engine.spark.SparkSQLEngine.initialize(SparkSQLEngine.scala:50)
	at org.apache.kyuubi.engine.spark.SparkSQLEngine$.startEngine(SparkSQLEngine.scala:108)
	at org.apache.kyuubi.engine.spark.WithSparkSQLEngine.startSparkEngine(WithSparkSQLEngine.scala:57)
	at org.apache.kyuubi.engine.spark.WithSparkSQLEngine.startSparkEngine$(WithSparkSQLEngine.scala:39)
	at org.apache.kyuubi.jdbc.KyuubiDriverSuite.startSparkEngine(KyuubiDriverSuite.scala:25)
	at org.apache.kyuubi.engine.spark.WithSparkSQLEngine.beforeAll(WithSparkSQLEngine.scala:35)
	at org.apache.kyuubi.engine.spark.WithSparkSQLEngine.beforeAll$(WithSparkSQLEngine.scala:34)
	at org.apache.kyuubi.jdbc.KyuubiDriverSuite.beforeAll(KyuubiDriverSuite.scala:25)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at org.apache.kyuubi.jdbc.KyuubiDriverSuite.run(KyuubiDriverSuite.scala:25)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1322)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1316)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1316)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1482)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:133)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)
Caused by: java.lang.ExceptionInInitializerError
	at org.apache.kyuubi.package$.<init>(package.scala:51)
	at org.apache.kyuubi.package$.<clinit>(package.scala)
	at org.apache.kyuubi.service.authentication.PlainSASLServer$.<init>(PlainSASLServer.scala:130)
	at org.apache.kyuubi.service.authentication.PlainSASLServer$.<clinit>(PlainSASLServer.scala)
	at org.apache.kyuubi.service.authentication.PlainSASLServer$SaslPlainProvider.<init>(PlainSASLServer.scala:135)
	at org.apache.kyuubi.service.authentication.PlainSASLHelper$.<init>(PlainSASLHelper.scala:36)
	at org.apache.kyuubi.service.authentication.PlainSASLHelper$.<clinit>(PlainSASLHelper.scala)
	at org.apache.kyuubi.service.authentication.KyuubiAuthenticationFactory.getTTransportFactory(KyuubiAuthenticationFactory.scala:74)
	at org.apache.kyuubi.service.FrontendService.initialize(FrontendService.scala:74)
	... 32 more
Caused by: java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at org.apache.kyuubi.package$BuildInfo$.<init>(package.scala:33)
	at org.apache.kyuubi.package$BuildInfo$.<clinit>(package.scala)
	... 41 more
```

#### 4.2 Log of the corresponding engine

**Comment by yaooqinn** [comment]
looks like we need to add a check for the existence of `kyuubi-version-info.properties` which is need a maven plugin to generate.

**Comment by yanghua** [comment]
> looks like we need to add a check for the existence of `kyuubi-version-info.properties` which is need a maven plugin to generate.

Figured out I need to invoke `mvn generate-sources` in my local to generate this file. But failed to download the dependencies from the apache snapshot repository.

**Comment by yanghua** [comment]
@yaooqinn IMO, we need to do some defensive check for this, and give more friendly guide for users especially for newbie. WDYT?

**Comment by yaooqinn** [comment]
Yes, we and add an explicit null check in `org.apache.kyuubi.package` for it to give better error msg

**Comment by yaooqinn** [comment]
> > looks like we need to add a check for the existence of `kyuubi-version-info.properties` which is need a maven plugin to generate.
> 
> Figured out I need to invoke `mvn generate-sources` in my local to generate this file. But failed to download the dependencies from the apache snapshot repository.

we have not set up maven repo yet, thanks for pointing this out

**Comment by yanghua** [comment]
> > looks like we need to add a check for the existence of `kyuubi-version-info.properties` which is need a maven plugin to generate.
> 
> Figured out I need to invoke `mvn generate-sources` in my local to generate this file. But failed to download the dependencies from the apache snapshot repository.

sounds good. after you publish the snapshot version, please feel free to ping me.

**Comment by yaooqinn** [comment]
> Yes, we and add an explicit null check in `org.apache.kyuubi.package` for it to give better error msg

can you send a PR for this？

**Comment by yanghua** [comment]
> > Yes, we and add an explicit null check in `org.apache.kyuubi.package` for it to give better error msg
> 
> can you send a PR for this？

sure, in addition, add more guide(invoke the `mvn generate-sources` command) for the setup/dev/quick-start documentation?

**Comment by yaooqinn** [comment]
Ah, I see. I just realized that Kyuubi is not developer-friendly enough.

Maybe we can add something like http://spark.apache.org/developer-tools.html. And we can start with a section where contributors can learn how to set up and test in IDEs, or something.

**Comment by yanghua** [comment]
> Ah, I see. I just realized that Kyuubi is not developer-friendly enough.
> 
> Maybe we can add something like http://spark.apache.org/developer-tools.html. And we can start with a section where contributors can learn how to set up and test in IDEs, or something.

+1

**Comment by yanghua** [comment]
> Ah, I see. I just realized that Kyuubi is not developer-friendly enough.
> 
> Maybe we can add something like http://spark.apache.org/developer-tools.html. And we can start with a section where contributors can learn how to set up and test in IDEs, or something.

Let's create a new issue to track this idea and move the discussion under that? WDYT?

**Comment by yaooqinn** [comment]
sgtm

**Comment by yanghua** [comment]
Moved the further discussion to issue #829 , closing this...
