### ISSUE TITLE
Improper exception for closing a non-existent session

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#821]
### 1. Describe the bug

Improper exception for closing a non-existent session

```
org.apache.kyuubi.KyuubiSQLException: Invalid SessionHandle [93904f38-0dcc-478a-8a39-1e7647a18677]
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:68)
	at org.apache.kyuubi.session.SessionManager.closeSession(SessionManager.scala:70)
	at org.apache.kyuubi.service.AbstractBackendService.closeSession(AbstractBackendService.scala:49)
	at org.apache.kyuubi.service.FrontendService$FeTServerEventHandler.deleteContext(FrontendService.scala:527)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:300)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

if the session being requested to close is null, we only need a warning here

#### 2.1 Versions

- Kyuubi
  - [ ] 1.1.0
  - [ ] 1.0.3
  - [ ] 0.8.x and earlier 

- Spark
  - [ ] 3.1.x
  - [ ] 3.0.x
  - [ ] 2.4.x and earlier 

#### 4.2 Log of the corresponding engine

**Comment by wuchunfu** [comment]
@yaooqinn I'll fix it.
